"""
Builds data/activities.json from the v1 inventory spreadsheet.

The spreadsheet stays the source of truth for IDs, titles, categories and
cost/time ranges. Everything the recommender needs (fixed enums, typical
cost/time, wildcard score, copy) is authored below, one entry per row, so
every change against the source is visible in code review.

Run: npm run data  (needs: pip install openpyxl)
"""

import json
import pathlib
import re

import openpyxl

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "source" / "v1-inventory.xlsx"
OUT = ROOT / "data" / "activities.json"

ENERGY = {"V": "very-low", "L": "low", "M": "medium", "H": "high"}
COMPANY = {"Solo": "solo", "Couple": "partner", "Friend": "friends", "Family": "family"}
SETTING = {
    "Home": ["home"],
    "Local": ["local"],
    "Nearby travel": ["travel"],
    "Home/Out": ["home", "local"],
    "Local/Home": ["local", "home"],
    "Anywhere": ["home", "local"],
}
ENVIRONMENT = {
    "Indoor": ["indoor"],
    "Outdoor": ["outdoor"],
    "Mixed": ["mixed"],
    "Indoor/Mixed": ["indoor", "mixed"],
}
# Spreadsheet "Personality" -> fixed enum. Rows can override with "p".
PERSONALITY = {
    "Sensible": ["sensible"],
    "Wholesome": ["wholesome"],
    "Cosy": ["cosy"],
    "Quirky": ["quirky"],
    "Silly": ["silly"],
    "Active": ["active"],
    "Crafty": ["crafty"],
    "Hobbyist": ["hobbyist"],
    "Adventurous": ["adventurous"],
    "Lively": ["active"],
    "Playful": ["silly"],
    "Practical": ["sensible"],
    "Reflective": ["wholesome"],
    "Bold": ["adventurous"],
    "Creative": ["crafty"],
}

# Shorthand used below:
#   e   energy levels it suits (V/L/M/H)
#   f   feelings, dominant first
#   a   actions, main first (default: from the sheet)
#   c   extra company types beyond the sheet
#   st  setting override
#   pl  planning: now | same-day | booking (default: booking if the sheet says so, else same-day)
#   cost / time  (min, typical, max) overrides; otherwise sheet min/max and an authored typical
#   tc / tt  typical cost / typical minutes
#   w   wildcard score 0-100
#   t / s  title / summary rewrites (only where the sheet copy needed it)
#   why / better  consumer copy
A = {
"WTY001": dict(e="MH", f=["novelty", "perspective", "outside"], tc=15, tt=240, w=78, p=["adventurous", "wholesome"],
    s="Pick a station you've never been to, buy a cheap return and wander without a plan.",
    why="A change of postcode does a lot of heavy lifting. The train does the rest.",
    better="Get off one stop early and walk the last bit in."),
"WTY002": dict(e="LM", f=["novelty", "outside", "distraction"], c=["friends"], tc=5, tt=180, w=55,
    s="See the landmarks, museums and odd little attractions you normally walk straight past.",
    why="Everything's already there. You just have to look at it like a visitor.",
    better="Buy a postcard of your own town and send it to someone."),
"WTY003": dict(e="LM", f=["novelty", "distraction", "calm"], c=["friends"], tc=0, tt=90, cost=(0, 0, 10), time=(45, 90, 240), a=["go", "learn"], pl="same-day",
    s="Pick one room or subject that genuinely interests you and browse it slowly.",
    why="Free, warm, quiet, and full of things that aren't about you.",
    better="Only read the labels of things you'd actually want to own."),
"WTY004": dict(e="VLM", f=["calm", "novelty"], c=["family"], tc=0, tt=75, cost=(0, 0, 15), time=(45, 75, 180),
    s="Wander a gallery until you find one piece you actually like, then stay with it a while.",
    why="Low effort, quiet, and nobody expects you to talk.",
    better="Find the worst painting in the building and decide what it's called."),
"WTY005": dict(e="LM", f=["laughter", "distraction", "connection"], tc=12, tt=150, w=45, pl="booking",
    s="Find a small club, a work-in-progress night or a local act rather than a big tour.",
    why="Hard to stay in your own head when a room full of strangers is laughing.",
    better="Sit near the back if you'd rather not be spoken to."),
"WTY006": dict(e="LM", f=["novelty", "laughter", "connection"], c=["family"], tc=10, tt=150, w=62, pl="booking",
    s="Find a community theatre, open-mic or local music night and take a chance on it.",
    why="Low stakes for you, high effort from everyone on stage. Something always happens.",
    better="Pick the listing with the most baffling description."),
"WTY007": dict(e="MH", f=["novelty", "distraction", "connection"], tc=10, tt=180, w=60, pl="booking",
    s="Go to a small local venue and see a band you've never heard of.",
    why="Loud enough to drown out whatever's going on in your head.",
    better="Buy the band's cheapest bit of merch if they're any good."),
"WTY008": dict(e="VL", f=["distraction", "comfort"], tc=12, tt=150,
    s="Choose something immersive, turn your phone off and disappear for two hours.",
    why="A dark room, a big screen and zero obligations. Nobody knows you're there.",
    better="Go to the earliest showing of the day; you'll have the place to yourself."),
"WTY009": dict(e="LM", f=["distraction", "novelty"], c=["friends"], tc=15, tt=240,
    s="Pair a film with a nearby gallery or museum for a low-effort mini day out.",
    why="Two easy things back to back feels like a proper day out without any planning.",
    better="Get lunch somewhere you've never tried in between."),
"WTY010": dict(e="MH", f=["play", "distraction", "laughter"], c=["partner"], tc=12, tt=90, w=30,
    s="Play a game or two, alone or with company, and don't care about the score.",
    why="Heavy ball, loud noise, clear goal. Your brain gets something simple to do.",
    better="Everyone has to bowl with their wrong hand for one frame."),
"WTY011": dict(e="LMH", f=["play", "laughter", "outside"], tc=10, tt=75, w=58,
    s="Pick the tackiest course you can find and lean into it.",
    why="Nobody's good at it and nobody's meant to be. That's the whole point.",
    better="Loser buys the ice cream."),
"WTY012": dict(e="H", f=["play", "distraction"], c=["family"], tc=30, tt=60, cost=(20, 30, 40), w=70, pl="booking",
    t="Go karting",
    s="Book a short session somewhere cheap and drive like nobody's watching.",
    why="You can't brood at 40mph. It takes your whole brain, briefly.",
    better="Pick a karting name for the scoreboard and commit to it."),
"WTY013": dict(e="MH", f=["achievement", "distraction", "play"], tc=15, tt=90, w=64, p=["active", "adventurous"],
    s="Book a beginner session or open climb and focus on one easy route at a time.",
    why="Each route is a small, obvious win. Your arms will be too tired to worry.",
    better="Finish on a route you've already done so you leave on a win."),
"WTY014": dict(e="LM", f=["connection", "play", "laughter"], tc=10, tt=120, w=35, c=["partner"],
    s="Find a pub board or book a darts lane and make the game the point.",
    why="Gives everyone something to do with their hands, so talking gets easier.",
    better="Invent a ridiculous forfeit for last place."),
"WTY015": dict(e="MH", f=["play", "connection", "achievement"], tc=25, tt=75, w=55, pl="booking", p=["active", "quirky"],
    s="Look for off-peak or smaller-room deals and solve something together.",
    why="An hour where the only problem is somebody else's fake one.",
    better="Ask for the easier room. Winning is more fun than learning."),
"WTY016": dict(e="VL", f=["distraction", "play", "achievement"], tc=18, tt=150, st=["home"], pl="now",
    t="Solve a murder mystery case file",
    s="Buy a boxed or downloadable case and spend an evening working it out.",
    why="A contained puzzle with an ending. Your brain gets a job that isn't you.",
    better="Print the downloadable bits and pin them to a wall with string."),
"WTY017": dict(e="LM", f=["calm", "outside", "perspective"], c=["friends"], tc=5, tt=180, time=(90, 180, 300), w=40,
    s="Pack what's already in the kitchen, pick a castle, beach or viewpoint, and make the view the treat.",
    why="Food tastes better outside and the view does the thinking for you.",
    better="Bring a flask. It turns a snack into an occasion."),
"WTY018": dict(e="MH", f=["outside", "perspective", "novelty"], c=["friends"], tc=15, tt=300, w=50,
    s="Get the bus, walk the front, and come home when you've had enough.",
    why="The sea is very good at making problems look smaller.",
    better="Chips on the wall. Non-negotiable."),
"WTY019": dict(e="MH", f=["outside", "achievement", "perspective"], c=["family"], tc=0, tt=120, cost=(0, 0, 10), time=(45, 120, 240), pl="now",
    s="Pick an achievable route with a proper view at the top.",
    why="Legs busy, head quieter, and a view you actually earned.",
    better="Take a photo at the top from exactly the same spot every time you go back."),
"WTY020": dict(e="MH", f=["outside", "calm", "connection"], tc=0, tt=90, cost=(0, 0, 10), time=(45, 90, 180), pl="now",
    t="Go for a walk and have a good moan",
    s="Walk somewhere open, beach if you've got one, vent to yourself or someone you trust, and keep going until your head's quieter.",
    why="Walking and moaning are both better together. It's practically science.",
    better="Set a moan limit: once you pass the bench, you're only allowed to talk about nice things."),
"WTY021": dict(e="LM", f=["comfort", "outside", "calm"], c=["friends"], tc=8, tt=150, w=45,
    s="Spend an hour or two around rescued animals and take a few photos to keep.",
    why="Animals don't care how you're feeling. Weirdly, that helps.",
    better="Leave a quid in the donation box and read the name board on the way out."),
"WTY022": dict(e="LM", f=["play", "comfort", "outside"], tc=10, tt=120, w=40,
    s="Find somewhere informal where you're allowed to get close to the animals.",
    why="It's hard to take yourself seriously while a goat eats your sleeve.",
    better="Decide which animal is your favourite and why, out loud."),
"WTY023": dict(e="VL", f=["calm", "outside", "play"], c=["friends"], tc=2, tt=45, cost=(0, 2, 15), time=(20, 45, 120), pl="now", w=35,
    s="Take oats, peas or proper duck food (not bread) and spend a while by the water.",
    why="Tiny effort, very grateful audience, and you're outside without trying.",
    better="Name the most aggressive duck. There's always one."),
"WTY024": dict(e="MH", f=["novelty", "outside", "calm"], tc=25, tt=90, w=68, pl="booking", p=["active", "adventurous"],
    s="Find a local hire point and paddle somewhere quiet, if the weather's on your side.",
    why="The water's calm, your arms are busy, and your phone is safely in a dry bag.",
    better="Aim for a pub or café reachable by water."),
"WTY025": dict(e="LM", f=["laughter", "novelty", "play"], c=["partner", "family"], tc=5, tt=60, w=72, p=["silly", "quirky"],
    t="Buy the weirdest thing you can find in a charity shop",
    s="Try two or three charity shops with one rule: you can only buy something that genuinely makes you laugh.",
    why="Cheap, low-pressure, gets you out, and gives your brain something harmless to hunt for.",
    better="Send photos of the three worst options to a friend and make them choose."),
"WTY026": dict(e="VL", f=["calm", "novelty", "comfort"], tc=5, tt=60,
    s="Leave with one book chosen purely because it caught your eye.",
    why="Quiet, slightly dusty, and no algorithm telling you what to like.",
    better="Check the inside cover for an old inscription. Half the fun is the stranger."),
"WTY027": dict(e="VL", f=["calm", "novelty", "outside"], c=["friends"], tc=8, tt=90, env=["mixed"], w=50, p=["wholesome", "quirky"],
    s="Wander, laugh at the ridiculous ornaments, and buy one small plant if you fancy it.",
    why="Warm, green, calm, and there's usually cake.",
    better="Find the ugliest ornament in the place and photograph it for posterity."),
"WTY028": dict(e="M", f=["novelty", "play", "distraction"], tc=15, tt=90, w=66, pl="booking",
    s="Rummage through clothes sold by weight and come home with one unexpected thing.",
    why="A treasure hunt with a price tag. Easy to lose an hour in it.",
    better="Set a 'most ridiculous jacket' challenge if you go with someone."),
"WTY029": dict(e="LM", f=["novelty", "calm", "connection"], c=["friends"], tc=10, tt=90, w=40,
    s="Wander with no obligation to buy, then choose one small handmade thing if something clicks.",
    why="People who've made something are usually happy to talk about it. Easy company.",
    better="Ask a maker how they made the thing you bought."),
"WTY030": dict(e="VL", f=["comfort", "distraction", "calm"], tc=12, tt=120, time=(15, 120, 480), st=["home", "local"], w=10,
    s="Pick a book you're genuinely excited to start tonight.",
    why="Something to look forward to by bedtime, and a good excuse to stay in.",
    better="Buy it in person and read the first chapter in the café next door."),
"WTY031": dict(e="V", f=["comfort", "distraction", "laughter"], tc=8, tt=120, time=(15, 120, 480), st=["home", "local"], w=20, pl="now",
    t="Buy an easy, trashy read",
    s="Choose something fun and undemanding that lets your brain switch off.",
    why="No improving yourself tonight. Just a plot that does all the work.",
    better="Read it in the bath."),
"WTY032": dict(e="VL", f=["distraction", "novelty", "comfort"], tc=15, tt=120, time=(15, 120, 480), st=["home", "local"], w=15,
    s="Get the first book or two of a series people won't stop going on about.",
    why="Sorts out the next few weeks of evenings in one go.",
    better="Ask a friend for their favourite series and read it at the same time."),
"WTY033": dict(e="VL", f=["distraction", "novelty"], tc=12, tt=90, st=["home", "local"], w=30,
    s="Pick something visually rich that feels easier to start than a big novel.",
    why="Pictures do half the work, so it's reading for tired brains.",
    better="Go to a comic shop and ask whoever's behind the counter for a recommendation."),
"WTY034": dict(e="V", f=["comfort", "distraction"], tc=10, tt=90, time=(15, 90, 480), a=["buy", "do"], pl="now", w=10,
    t="Get an audiobook you can disappear into",
    s="Choose a series or a narrator you'd happily listen to without looking at a screen.",
    why="Someone reads you a story. Your eyes get the night off.",
    better="Listen in the dark with a hot drink. Nothing else."),
"WTY035": dict(e="VL", f=["comfort", "distraction"], c=["friends"], tc=6, tt=150, st=["home", "local"], w=15,
    t="Buy a film you love and make an event of it",
    s="Pick a film you'll genuinely rewatch and do it properly: lights off, snacks, no phone.",
    why="A known good thing. No risk, all comfort.",
    better="Pause it at your favourite bit and tell whoever's with you why it's the best bit."),
"WTY036": dict(e="V", f=["comfort", "distraction"], tc=10, tt=240, time=(120, 240, 480), st=["home", "local"], w=10,
    s="Browse a second-hand shop, pick a whole series, then put your phone on Do Not Disturb.",
    why="Physical box sets feel like a treat in a way streaming never does.",
    better="Choose one you watched years ago and see if it holds up."),
"WTY037": dict(e="VL", f=["comfort", "calm"], tc=18, tt=60, st=["home", "local"], w=25,
    s="Pick an album you love, or the one you've always meant to own properly.",
    why="Putting a record on is a small ritual. You can't skip; you just listen.",
    better="Buy it in a record shop and let the person behind the counter recommend a second one."),
"WTY038": dict(e="VL", f=["distraction", "play"], tc=15, tt=120, time=(30, 120, 480), pl="now", w=15,
    s="Choose one you already wanted rather than scrolling endlessly for something new.",
    why="Decision already made. Straight to the fun bit.",
    better="Play the first hour with no guides or wikis."),
"WTY039": dict(e="VL", f=["achievement", "distraction", "calm"], c=["friends"], tc=15, tt=90, time=(30, 90, 180), st=["home", "local"], w=25, p=["hobbyist", "silly"],
    s="Pick one small set you can finish in a single sitting.",
    why="Clear instructions, a finished thing at the end, and no way to do it wrong.",
    better="Do it with music on and your phone in another room."),
"WTY040": dict(e="VL", f=["calm", "achievement"], tc=25, tt=120, cost=(12, 25, 40), st=["home", "local"], w=25, p=["crafty", "wholesome"],
    t="Build a Lego flower",
    s="Make one of the botanical sets. It doubles as cheerful room decoration afterwards.",
    why="Methodical, calming, and you end up with flowers that won't die.",
    better="Put it somewhere you'll see first thing in the morning."),
"WTY041": dict(e="L", f=["achievement", "distraction", "calm"], tc=20, tt=180, st=["home", "local"], w=30,
    s="Try a snap-fit Gunpla, Airfix or similar starter kit.",
    why="Small, fiddly, absorbing. It's very hard to worry and glue at the same time.",
    better="Give it a name and a backstory once it's finished."),
"WTY042": dict(e="L", f=["calm", "distraction", "achievement"], tc=20, tt=180, time=(90, 180, 480), w=48, p=["crafty", "quirky"],
    s="Build a tiny room, shop or scene over a few evenings.",
    why="Tiny things need your full attention. That's the trick.",
    better="Hide one thing in the scene that only you know about."),
"WTY043": dict(e="VL", f=["calm", "distraction", "achievement"], c=["friends"], tc=10, tt=180, time=(45, 180, 360), st=["home", "local"], w=10,
    s="Pick a picture you'll actually enjoy looking at for a few hours.",
    why="Slow, satisfying and endlessly forgiving. It's fine to leave it on the table for a week.",
    better="Get one from a charity shop. The missing piece is part of the adventure."),
"WTY044": dict(e="V", f=["distraction", "achievement", "calm"], tc=8, tt=60, cost=(3, 8, 15), time=(15, 60, 180), st=["home", "local"], w=10,
    s="Crosswords, logic puzzles or sudoku, with a pen that feels nice to use.",
    why="Small puzzles, small wins. Your brain gets tidied a square at a time.",
    better="Do one in a café so it feels like a trip out."),
"WTY045": dict(e="V", f=["calm", "distraction"], tc=15, tt=60, st=["home", "local"], w=20,
    s="Spend more on the pens than the paper, and enjoy using them for ages.",
    why="A good pen on paper is a small, dependable pleasure.",
    better="Colour something in a completely wrong colour scheme on purpose."),
"WTY046": dict(e="V", f=["calm", "distraction"], tc=6, tt=60, st=["home", "local"], w=20,
    s="Choose detailed, funny or cosy pages and colour them without trying to be good at it.",
    why="There's no wrong answer and nothing to decide except which blue.",
    better="Pick a sweary colouring book. It's more cathartic than it has any right to be."),
"WTY047": dict(e="L", f=["comfort", "achievement", "connection"], c=["friends"], tc=10, tt=90, cost=(0, 10, 25), time=(45, 90, 180), st=["home"], w=30,
    s="Print a few photos and make one page, rather than trying to document your whole life.",
    why="Looking back at good days is a gentle reminder that there'll be more.",
    better="Add a ticket stub or receipt from the day. It's always the tiny stuff."),
"WTY048": dict(e="L", f=["achievement", "distraction"], tc=12, tt=120, st=["home", "local"], w=25,
    s="Pick a small kit with everything included and a clear finished object at the end.",
    why="All the thinking's been done for you. You just get to make the thing.",
    better="Give the finished thing to someone, however wonky."),
"WTY049": dict(e="LM", f=["achievement", "calm"], tc=20, tt=150, time=(60, 150, 300), st=["home", "local"], w=55, p=["crafty", "hobbyist"],
    s="Start with a beginner blank and make something deliberately imperfect.",
    why="Slow, rhythmic and forgiving. Plus you get to hold a knife and feel capable.",
    better="Carve a spoon. It's the classic first project for a reason."),
"WTY050": dict(e="L", f=["achievement", "novelty", "connection"], c=["family"], tc=35, tt=120, cost=(20, 35, 50), w=58,
    s="Find a taster session where someone else handles the materials and the clean-up.",
    why="Muddy hands, a teacher, and a lopsided bowl to take home. All the fun, none of the mess.",
    better="Make something for someone else. It'll be terrible and they'll love it."),
"WTY051": dict(e="L", f=["play", "laughter", "achievement"], tc=10, tt=45, time=(20, 45, 120), st=["home", "local"], w=76, p=["silly", "quirky"],
    s="Learn one recognisable tune badly and enjoy the novelty.",
    why="Nobody expects you to be good at harmonica. Freeing, really.",
    better="Learn the theme tune to something daft and perform it for one lucky person."),
"WTY052": dict(e="L", f=["achievement", "play", "novelty"], tc=30, tt=60, time=(30, 60, 120), st=["home", "local"], w=55,
    s="Learn three chords and one simple song over the next week.",
    why="Small, cheerful, and you'll be playing an actual song within an hour.",
    better="Film yourself playing it on day one and day seven."),
"WTY053": dict(e="VL", f=["novelty", "achievement", "distraction"], tc=12, tt=60, time=(30, 60, 180), pl="now", w=30,
    s="Choose a topic you've always been curious about, not one that's 'useful'.",
    why="Learning something for no reason is a good reminder that you're more than your to-do list.",
    better="Tell someone one fact from lesson one."),
"WTY054": dict(e="V", f=["novelty", "distraction", "perspective"], tc=0, tt=60, cost=(0, 0, 0), time=(15, 60, 120), pl="now", w=35,
    t="Watch a lecture on something you know nothing about",
    s="Pick one subject you've never looked into and give it an hour, or a short talk if that's all you've got.",
    why="Borrow someone else's enthusiasm for an hour. It's free and it's catching.",
    better="Pick the most obscure topic you can find. Medieval plumbing. Competitive bird calling."),
"WTY055": dict(e="V", f=["comfort", "achievement"], tc=12, tt=30, time=(15, 30, 60), st=["home", "local"], w=10,
    s="Give yourself guilt-free permission to buy the small thing you keep talking yourself out of.",
    why="Future-you gets a nudge back into something they already enjoy.",
    better="Use it tonight, even for ten minutes."),
"WTY056": dict(e="L", f=["novelty", "achievement"], tc=15, tt=120, st=["home", "local"], w=45,
    s="Pick one kit with a low barrier to entry and see whether it sticks.",
    why="No commitment. If it's not for you, you've lost an evening and a tenner.",
    better="Pick one you'd have loved at age ten."),
"WTY057": dict(e="L", f=["calm", "achievement", "distraction"], tc=20, tt=180, st=["home", "local"], w=35,
    t="Buy one wargaming miniature",
    s="Choose a single model or a small kit, rather than committing to an army.",
    why="Tiny brush, tiny details, total absorption.",
    better="Paint it in a colour scheme nobody would approve of."),
"WTY058": dict(e="V", f=["comfort", "laughter"], tc=10, tt=30, st=["home", "local"], w=55, p=["silly", "cosy"],
    s="Find a small toy, figure or object linked to something you adored as a kid.",
    why="Instant route back to a version of you that wasn't worrying about this.",
    better="Put it somewhere you'll see it at work or at your desk."),
"WTY059": dict(e="V", f=["laughter", "novelty"], tc=10, tt=30, cost=(3, 10, 25), time=(15, 30, 60), st=["home", "local"], w=85,
    t="Buy a weird, niche ornament",
    s="Choose something so specific it feels like an inside joke with yourself.",
    why="It'll make you laugh every time you walk past it for years.",
    better="Give it a name and never explain it to visitors."),
"WTY060": dict(e="V", f=["comfort", "laughter"], tc=10, tt=15, st=["home", "local"], w=50,
    t="Buy a mug that makes you grin",
    s="One cheerful, unnecessary mug. Gromit is traditional.",
    why="You'll use it every day, which means a small daily grin.",
    better="Make the first tea in it the best one you've made all month."),
"WTY061": dict(e="V", f=["novelty", "play", "laughter"], c=["partner"], tc=10, tt=30, time=(20, 30, 60), w=92,
    s="Set up a tiny, ridiculous aquatic civilisation on your desk.",
    why="It's absurd, it's cheap and you'll have something to check on every morning.",
    better="Name them after people you work with."),
"WTY062": dict(e="V", f=["comfort", "laughter"], tc=12, tt=20, st=["home", "local"], w=40,
    s="Pick one for no reason beyond it being comforting or funny.",
    why="Adults are allowed soft things. Nobody needs to know.",
    better="Choose the one with the most confused face."),
"WTY063": dict(e="V", f=["comfort"], tc=18, tt=30, st=["home", "local"], w=5,
    s="Get a set that makes going to bed feel slightly more deliberate.",
    why="Putting on nice pyjamas is a clear signal that the day's done.",
    better="Wash the sheets the same day. Clean sheets and new pyjamas is elite."),
"WTY064": dict(e="V", f=["comfort", "laughter"], tc=15, tt=20, st=["home", "local"], w=25,
    s="Choose the pair you'd normally decide is too expensive for socks.",
    why="Cheap luxury you'll feel every time you put your feet up.",
    better="Get a pattern you'd never usually wear."),
"WTY065": dict(e="V", f=["comfort"], tc=6, tt=20, st=["home", "local"], w=5,
    s="Get the softest pair you can find and wear them immediately.",
    why="Small, warm and silly. Cold feet make everything worse.",
    better="Buy two pairs and give one away."),
"WTY066": dict(e="V", f=["comfort"], tc=15, tt=20, st=["home", "local"], w=5,
    s="Replace the sad old pair, or buy some for the first time.",
    why="Being warm and comfortable at home isn't a small thing when you feel rubbish.",
    better="Ceremonially bin the old ones."),
"WTY067": dict(e="V", f=["comfort"], tc=25, tt=20, st=["home", "local"], w=5,
    s="Choose one that makes staying in feel deliberate rather than defeated.",
    why="Staying in is fine. Staying in properly is better.",
    better="Get one that's slightly too big."),
"WTY068": dict(e="V", f=["comfort", "calm"], c=["friends"], tc=18, tt=20, st=["home", "local"], w=5,
    s="Choose texture over practicality and put it straight on the sofa.",
    why="Being physically comfortable is half the battle some days.",
    better="Wash it once before using it. It gets softer."),
"WTY069": dict(e="V", f=["comfort", "calm"], tc=25, tt=20, w=5,
    s="Make one spot in the house reliably warm and inviting.",
    why="A warm bed on a cold night is one of life's best cheap pleasures.",
    better="Switch it on half an hour before bed so it's ready."),
"WTY070": dict(e="V", f=["comfort", "calm"], tc=20, tt=20, w=5,
    s="Get a rechargeable one for cold evenings or aching shoulders.",
    why="Warmth is comforting in a way that doesn't need explaining.",
    better="Get one with a cover you like touching."),
"WTY071": dict(e="V", f=["comfort", "calm"], tc=20, tt=30, st=["home", "local"], w=5,
    s="Buy one good cotton sheet rather than a whole bedding set.",
    why="You spend a third of your life on it. Might as well be nice.",
    better="Change the bed tonight, not at the weekend."),
"WTY072": dict(e="V", f=["comfort", "calm"], tc=18, tt=30, st=["home", "local"], w=5,
    s="Replace the pillow you complain about every night.",
    why="A small fix you'll feel every single night.",
    better="Swap it tonight, then put the old one in the car for road trips."),
"WTY073": dict(e="V", f=["comfort", "calm"], tc=15, tt=20, w=35,
    s="Makes screen-free audiobooks or podcasts in bed much easier.",
    why="Dark, quiet and a voice telling you a story. Bedtime sorted.",
    better="Pair it with a sleep story you'd never admit to choosing."),
"WTY074": dict(e="V", f=["comfort", "calm"], tc=12, tt=20, st=["home", "local"], w=10,
    s="Choose the scent by smell, not by what sounds sophisticated.",
    why="Smell changes how a room feels faster than anything else.",
    better="Light it when you get home, not just on special occasions."),
"WTY075": dict(e="V", f=["calm", "comfort"], tc=12, tt=20, st=["home", "local"], w=10,
    s="Change how one room smells as a small reset.",
    why="The room feels different, so you feel a bit different in it.",
    better="Put it in the hallway so home smells nice when you walk in."),
"WTY076": dict(e="V", f=["comfort", "calm"], tc=10, tt=75, cost=(0, 10, 25), w=15, pl="now",
    t="Have a cheap pamper evening",
    s="Pick two or three things: a bath bomb, a face mask, nail polish. Or use what's already in the cupboard.",
    why="Taking care of yourself in small, physical ways often lands better than thinking about it.",
    better="Put on a film you know every word of while the face mask dries."),
"WTY077": dict(e="V", f=["comfort", "novelty"], tc=6, tt=20, st=["home", "local"], w=15,
    s="Choose a scent that makes an ordinary shower feel slightly new.",
    why="A tiny change to something you do every day. Cheap, but you notice.",
    better="Pick the most ridiculous scent on the shelf."),
"WTY078": dict(e="V", f=["comfort", "calm"], tc=10, tt=20, st=["home", "local"], w=20,
    s="Pick the bunch you'd normally only buy for someone else.",
    why="Flowers on the table make the whole room feel looked after, including you.",
    better="Buy the ones reduced for quick sale. They're still lovely."),
"WTY079": dict(e="V", f=["calm", "comfort", "achievement"], c=["friends"], tc=12, tt=30, st=["home", "local"], w=20,
    s="Choose one that suits your actual light and your actual attention span.",
    why="Something living that depends on you, a little. That's surprisingly good for you.",
    better="Give it a name. Plants with names get watered."),
"WTY080": dict(e="V", f=["novelty", "laughter", "calm"], tc=12, tt=30, st=["home", "local"], w=74, p=["quirky", "silly"],
    s="Pick something like a crocodile fern purely because the name makes you happy.",
    why="It's a plant, but it's also a joke. Both keep growing.",
    better="Make it a tiny name sign."),
"WTY081": dict(e="M", f=["achievement", "comfort"], tc=20, tt=120, cost=(0, 20, 25), w=30,
    s="Spend the budget on one set of small accessories and rearrange one room.",
    why="Change the room, change the mood. And it's done by teatime.",
    better="Move one piece of furniture. It makes it feel like a new room."),
"WTY082": dict(e="LM", f=["achievement", "comfort"], tc=8, tt=60, cost=(0, 8, 25), time=(15, 60, 180), w=20,
    s="Fix the thing you've been tolerating for months. Buy the small part or tool if you need it.",
    why="Tiny annoyances drain you. Fixing one gives you a disproportionate buzz.",
    better="Tell someone. Fixing things is only half as good if nobody knows."),
"WTY083": dict(e="V", f=["achievement", "distraction", "calm"], tc=12, tt=45, st=["home", "local"], w=60, p=["quirky", "sensible"],
    s="De-bobble jumpers, cushions and anything else until the novelty wears off.",
    why="Oddly, unreasonably satisfying. Instant visible progress.",
    better="Do the jumper you've stopped wearing because of the bobbles. Welcome back."),
"WTY084": dict(e="V", f=["comfort", "outside"], tc=15, tt=20, w=15,
    s="Give future-you a hot drink on walks, in parks and on cold touchlines.",
    why="Small upgrade, lots of better days out later.",
    better="Take it on a walk straight away."),
"WTY085": dict(e="V", f=["novelty", "play"], tc=15, tt=20, w=45, p=["quirky", "sensible"],
    s="A small, surprisingly good torch for walks, drawers and minor adventures.",
    why="It makes you want to go and look at something in the dark. That's the point.",
    better="Go for a short evening walk with it the same day."),
"WTY086": dict(e="V", f=["novelty", "play"], tc=20, tt=20, st=["home", "local"], w=40,
    s="Choose a small everyday model and enjoy carrying a tiny toolkit around.",
    why="Being prepared for anything feels good, even if anything is opening a parcel.",
    better="Learn what every single tool is actually for."),
"WTY087": dict(e="V", f=["comfort"], tc=18, tt=30, st=["home", "local"], w=5,
    s="Replace two tired pairs with ones that fit properly and feel good.",
    why="No one sees it, but you feel it all day.",
    better="Bin the worst pair on the same day."),
"WTY088": dict(e="L", f=["comfort", "achievement"], tc=30, tt=45, w=5,
    s="If you genuinely need shoes, turn the treat budget into a small everyday upgrade.",
    why="Comfortable feet make every walk more likely.",
    better="Wear them straight out of the shop."),
"WTY089": dict(e="L", f=["comfort", "novelty"], tc=20, tt=45, w=10,
    s="Pick one thing that makes you feel better as soon as you put it on.",
    why="Looking a bit more like yourself sometimes gets you feeling a bit more like yourself.",
    better="Wear it tomorrow, not 'for best'."),
"WTY090": dict(e="V", f=["comfort", "novelty"], tc=12, tt=30, st=["home", "local"], w=45,
    t="Buy an unexpectedly beautiful little bag",
    s="A pencil case, pouch or organiser, chosen simply because you like looking at it.",
    why="Nice objects in ordinary places make ordinary days a little better.",
    better="Put your least favourite things in it. Instant upgrade."),
"WTY091": dict(e="M", f=["achievement", "play", "connection"], c=["friends"], tc=25, tt=120, w=60, p=["hobbyist", "quirky"],
    s="Get a manual one and turn making dinner into the activity.",
    why="Hands busy, flour everywhere, and you eat the results.",
    better="Invite someone over to crank the handle."),
"WTY092": dict(e="V", f=["comfort", "novelty"], tc=15, tt=20, w=50,
    t="Buy proper noodle bowls and broth spoons",
    s="Upgrade one very specific meal ritual because it pleases you.",
    why="It's absurdly specific. That's why it feels like a treat.",
    better="Make instant noodles fancy tonight: an egg, spring onions, the works."),
"WTY093": dict(e="MH", f=["play", "outside", "laughter"], tc=15, tt=90, w=70, p=["active", "quirky"],
    t="Buy a cheap golf club and hit some balls",
    s="Find a used club and a few balls, take them to a practice area and hit badly without keeping score.",
    why="Hitting something as hard as you can is surprisingly good for a bad mood.",
    better="Name each ball after something that's annoying you."),
"WTY094": dict(e="V", f=["comfort", "achievement"], tc=18, tt=30, time=(15, 30, 60), st=["home", "local"], w=10,
    s="Choose the small upgrade that'll make you want to start the next project.",
    why="A nudge back towards something you already know makes you happy.",
    better="Start the next project tonight with it."),
"WTY095": dict(e="V", f=["calm", "perspective"], tc=0, tt=20, cost=(0, 0, 20), time=(10, 20, 60), pl="now", w=15, st=["home", "local"],
    s="Use any notebook, or buy one you like, and write one page with no rules.",
    why="Getting it out of your head and onto paper makes it smaller.",
    better="Write in a café. Something about other people's noise helps."),
"WTY096": dict(e="V", f=["calm", "distraction", "laughter"], tc=0, tt=30, cost=(0, 0, 15), time=(10, 30, 90), pl="now", w=40, p=["crafty", "silly"],
    s="Pencil, any paper, and whatever's in front of you. Badly is the brief.",
    why="Looking properly at one thing is a good way to stop looking at everything else.",
    better="Draw with your wrong hand. It's funnier."),
"WTY097": dict(e="L", f=["novelty", "comfort"], tc=35, tt=60, cost=(20, 35, 50), w=35, pl="booking",
    t="Get the piercing you've wanted for a while",
    s="Book something simple at a reputable studio, if it's something you've wanted for a while rather than a snap decision.",
    why="A small, permanent marker that you're still in charge of you.",
    better="Take a friend for moral support and lunch after."),
"WTY098": dict(e="V", f=["novelty", "comfort"], tc=18, tt=30, w=65, p=["quirky", "hobbyist"],
    t="Buy a small replica or curiosity",
    s="Find a small object linked to a niche interest: architecture, history, folklore.",
    why="Owning a little piece of the thing you nerd out about is a good reminder of who you are.",
    better="Learn one proper fact about it you can bore people with."),
"WTY099": dict(e="L", f=["connection", "play", "laughter"], tc=20, tt=120, time=(60, 120, 240), w=35, pl="same-day",
    s="Choose something quick to teach, then actually invite people round to play it.",
    why="Gives everyone something to do, so you don't have to make conversation.",
    better="Pick something with a 30-minute play time so you can go again."),
"WTY100": dict(e="LM", f=["connection", "outside", "perspective"], c=["partner", "family"], tc=0, tt=75, time=(30, 75, 150), pl="now", w=10,
    t="Ring a friend and go for a walk",
    s="Keep the plan simple: somewhere pleasant, no big agenda.",
    why="Side-by-side talking is easier than face-to-face. And you're outside.",
    better="Walk to somewhere that sells a hot drink."),
"WTY101": dict(e="LM", f=["connection", "comfort"], c=["partner"], tc=10, tt=45, cost=(1, 10, 25), time=(15, 45, 120), a=["give", "buy"], w=55, p=["wholesome"],
    t="Spend it on someone who needs cheering up",
    s="Turn your treat into a small gift or surprise for someone else.",
    why="Making someone's day better is one of the fastest ways to improve your own.",
    better="Deliver it in person. Don't just order it to their door."),
"WTY102": dict(e="LM", f=["connection", "play"], tc=5, tt=120, time=(45, 120, 300), w=20, pl="now",
    t="Share your hobby with your child",
    s="Let them choose something small connected to an interest you both enjoy.",
    why="Your attention is the best thing you can give them, and it's good for you too.",
    better="Let them be in charge for the whole afternoon."),
"WTY103": dict(e="LM", f=["perspective", "comfort", "outside"], c=["friends"], tc=0, tt=90, cost=(0, 0, 20), time=(45, 90, 240), w=45, pl="now",
    s="Go back to a park, street, museum or place that reminds you of an easier chapter.",
    why="A good reminder that you've been OK before, and you will be again.",
    better="Take a photo of the same spot you remember and send it to whoever was there then."),
"WTY104": dict(e="V", f=["comfort", "distraction"], tc=8, tt=30, st=["home", "local"], w=30,
    s="Find a second-hand copy of something that used to make you happy.",
    why="Nostalgia is a cheap, reliable comfort. No surprises, just the good bits.",
    better="Hunt for it in a charity shop first. The search is part of it."),
"WTY105": dict(e="LM", f=["novelty", "outside", "calm"], c=["partner"], tc=0, tt=60, cost=(0, 0, 10), time=(30, 60, 180), w=65, pl="now", p=["quirky", "crafty"],
    t="Go on a themed photo walk",
    s="Choose a theme, like doors, dogs or strange signs, and photograph only that.",
    why="A tiny mission changes how you see a street you've walked a hundred times.",
    better="Make a grid of your ten best and send it to someone."),
"WTY106": dict(e="V", f=["comfort", "novelty"], tc=15, tt=30, st=["home", "local"], w=25,
    s="Choose something that makes the room feel more like yours.",
    why="A blank wall is a small daily reminder of nothing. Fix it.",
    better="Buy from an artist at a market rather than a chain."),
"WTY107": dict(e="V", f=["comfort", "outside"], tc=15, tt=20, w=15,
    s="Makes winter walks, commutes and cold desks less miserable.",
    why="Cold hands make everything feel worse. Solve that bit.",
    better="Take it for a walk the day it arrives."),
"WTY108": dict(e="LM", f=["novelty", "play"], c=["family"], tc=20, tt=120, w=75, pl="booking", p=["adventurous", "quirky"],
    t="Book something you'd never normally book",
    s="Check a reputable local deals site for an activity you'd usually scroll past.",
    why="Future-you gets something to look forward to. That alone helps.",
    better="Pick the one you'd be most embarrassed to admit you booked."),
"WTY109": dict(e="LM", f=["novelty", "outside", "calm"], c=["friends"], tc=18, tt=210, w=35,
    s="Choose one with good grounds, so the trip still works if you tire of the interiors.",
    why="Big rooms, big gardens, and someone else's problems from 300 years ago.",
    better="Find the most pointless room in the house."),
"WTY110": dict(e="MH", f=["novelty", "outside", "play"], c=["friends"], tc=12, tt=150, w=45,
    s="Give yourself one historical rabbit hole for the afternoon.",
    why="Climbing up a castle keeps legs busy and brains elsewhere.",
    better="Work out where you'd have been posted if you'd lived there."),
"WTY111": dict(e="MH", f=["novelty", "distraction"], c=["friends"], tc=18, tt=120, w=80, pl="booking", p=["adventurous", "quirky"],
    t="Go underground",
    s="Find a public cave, mine or underground attraction and do something physically different.",
    why="Hard to feel stuck in a rut when you're literally underground.",
    better="Ask the guide what the weirdest thing they've found down there is."),
"WTY112": dict(e="MH", f=["outside", "calm", "perspective"], c=["family"], tc=10, tt=240, w=35,
    s="Pick the easiest nature spot you can reach without making the journey a project.",
    why="Green, quiet and far enough away that home feels properly paused.",
    better="Take a paper map. You'll look more interesting."),
"WTY113": dict(e="V", f=["calm", "comfort", "outside"], tc=0, tt=75, time=(30, 75, 180), w=25, pl="now",
    s="Take a book to a park, library, café or any quiet public space.",
    why="Same thing you'd do at home, but it counts as going out.",
    better="Stay for one more chapter than you planned."),
"WTY114": dict(e="LM", f=["play", "novelty", "laughter"], c=["friends"], tc=10, tt=180, w=82,
    t="Go somewhere new with a £5 souvenir challenge",
    s="Go somewhere new and allow exactly £5 for one magnet, postcard or ridiculous memento.",
    why="The rule turns a wander into a game. You'll look at every shop differently.",
    better="Whoever's with you gets a £5 too. Compare at the end. Best one wins."),
"WTY115": dict(e="V", f=["comfort", "distraction", "calm"], c=["family"], tc=0, tt=180, time=(60, 180, 360), w=10, pl="now",
    s="Do Not Disturb on, curtains shut, and a firm commitment to being unavailable.",
    why="Permission to be completely offline for an evening. Surprisingly rare.",
    better="Tell one person you're doing it so you can't cheat."),
"WTY116": dict(e="V", f=["calm", "comfort"], tc=10, tt=30, st=["home", "local"], w=25,
    s="Pick one smell, texture or sound: a candle, soap, blanket, record or diffuser.",
    why="Change one sense and the room feels different. So do you.",
    better="Do one sense tonight, then another next week."),
"WTY117": dict(e="L", f=["achievement", "comfort"], tc=6, tt=45, cost=(0, 6, 25), w=20, pl="now", p=["sensible"],
    s="List three things that irritate you daily, then solve the cheapest one.",
    why="A small, permanent improvement to every day from now on.",
    better="Stick the list somewhere and do the next one next week."),
"WTY118": dict(e="V", f=["laughter", "comfort"], tc=12, tt=15, time=(10, 15, 30), st=["home", "local"], w=80,
    t="Buy the ridiculous thing you keep looking at",
    s="If it's harmless, affordable, and still makes you laugh after a week, give in.",
    why="You've clearly already decided. This just saves time.",
    better="Tell someone what it is. They'll laugh too."),
"WTY119": dict(e="MH", f=["novelty", "play", "outside"], tc=8, tt=150, time=(60, 150, 240), w=88, pl="now",
    t="Go on a £10 micro-adventure",
    s="Set a hard £10 cap, leave the house, and see how much you can get out of it.",
    why="A limit turns an ordinary day out into a game.",
    better="Get a bus to the end of the line and see what's there."),
"WTY120": dict(e="LM", f=["novelty", "play", "laughter"], tc=0, tt=60, time=(15, 60, 240), w=50, pl="now", st=["home", "local"],
    t="Let a dice decide",
    s="Write down six things you could do today, roll a die and do what it says.",
    why="Taking the decision out of your hands is sometimes the whole problem solved.",
    better="Get someone else to write the list."),
}


# Free, at-home ideas added after the V1 review. The inventory leaned hard
# on buying things, and "£0, 15 mins, stay home" had almost nothing to offer.
# These aren't in the spreadsheet, so each entry is complete.
def extra(id, title, category, actions, cost, time, e, company, feelings, personality, novelty, w, summary, why, better,
          setting=("home",), environment=("indoor",), planning="now"):
    return {
        "id": id, "title": title, "summary": summary, "category": category,
        "cost": dict(zip(("min", "typical", "max"), cost)),
        "time": dict(zip(("minMinutes", "typicalMinutes", "maxMinutes"), time)),
        "energy": [ENERGY[x] for x in e], "company": list(company), "setting": list(setting),
        "environment": list(environment), "actions": list(actions), "feelings": list(feelings),
        "planning": planning, "novelty": novelty, "personality": list(personality), "wildcardScore": w,
        "whyItWorks": why, "makeItBetter": better, "source": {"type": "original"},
    }

ALL = ("solo", "partner", "friends", "family")

EXTRAS = [
    extra("WTY121", "Clear one surface completely", "Home", ["do"], (0, 0, 0), (10, 20, 45), "LM", ALL,
          ["achievement", "calm"], ["sensible"], "familiar", 10,
          "Pick one table, shelf or worktop and get it totally clear. Just the one.",
          "Small enough to finish, visible enough that you'll notice it every time you walk past.",
          "Put one nice thing back on it afterwards. Only one."),
    extra("WTY122", "Make the best hot drink you can", "Comfort", ["make"], (0, 0, 0), (10, 15, 30), "V", ALL,
          ["comfort", "calm"], ["cosy"], "familiar", 10,
          "Use what's already in the kitchen and make it properly: warmed mug, the good biscuits, sit down to drink it.",
          "Five minutes of doing one thing slowly and well. It counts.",
          "Drink it by a window, not a screen."),
    extra("WTY123", "Hold a three-song kitchen disco", "Move", ["do"], (0, 0, 0), (10, 15, 30), "MH", ALL,
          ["laughter", "play", "distraction"], ["silly", "active"], "new", 70,
          "Three songs, full volume, nobody watching. Dance like you're at a wedding at 11pm.",
          "Hard to stay flat when you're moving badly to something loud.",
          "Let someone else pick song two. No vetoes."),
    extra("WTY124", "Follow a free workout video badly", "Move", ["do"], (0, 0, 0), (15, 25, 45), "MH", ("solo", "partner", "family"),
          ["achievement", "distraction"], ["active"], "familiar", 25,
          "Pick a beginner video of 20 minutes or less and do it with zero concern for form or dignity.",
          "Someone else does the thinking; you just copy. Twenty minutes later you've moved.",
          "Pick the most over-enthusiastic instructor you can find."),
    extra("WTY125", "Cook something from whatever's in the cupboard", "Food", ["make"], (0, 0, 0), (30, 60, 90), "LM", ALL,
          ["achievement", "play"], ["crafty", "quirky"], "new", 55,
          "No shop. Pick three things you've already got and make them into a meal.",
          "It turns 'there's nothing in' into a small puzzle, and you get fed at the end.",
          "Give it a restaurant-menu name. 'Deconstructed beans on toast' is a strong start."),
    extra("WTY126", "Send a voice note to someone you miss", "Social", ["do"], (0, 0, 0), (5, 10, 20), "VL", ("solo",),
          ["connection", "comfort"], ["wholesome"], "familiar", 30,
          "Someone you haven't spoken to in ages. Two minutes, no reason needed.",
          "Reaching out without having to hold a whole conversation. They'll almost certainly be glad.",
          "Start with a memory: 'I just thought about the time we...'"),
    extra("WTY127", "Rewatch something you loved at fourteen", "Media", ["do"], (0, 0, 0), (25, 60, 180), "V", ALL,
          ["comfort", "laughter"], ["cosy"], "familiar", 30,
          "Find the first episode of a show you were obsessed with as a teenager, if you've got it on something already.",
          "Old favourites ask nothing of you, and they come with a better version of your past attached.",
          "Text someone who watched it with you back then."),
    extra("WTY128", "Build a proper blanket fort", "Silly", ["make"], (0, 0, 0), (20, 45, 120), "LM", ALL,
          ["play", "laughter", "comfort"], ["silly"], "new", 80,
          "Chairs, sofa cushions, every blanket in the house. Then get in it with a snack.",
          "You're too old for this, which is exactly why it works.",
          "Watch something from inside it on a laptop."),
    extra("WTY129", "Do the full reset: shower, clean clothes, open a window", "Self-care", ["do"], (0, 0, 0), (10, 20, 30), "V", ("solo",),
          ["comfort", "calm"], ["sensible"], "familiar", 5,
          "A quick shower, the comfiest clean thing you own, and five minutes of fresh air through an open window.",
          "It doesn't fix anything, but it changes how you feel in your own skin in twenty minutes.",
          "Put the bedsheets in the wash while you're at it."),
    extra("WTY130", "Make a playlist for an oddly specific moment", "Music", ["make"], (0, 0, 0), (15, 30, 60), "V", ALL,
          ["play", "laughter", "distraction"], ["quirky"], "new", 75,
          "Pick a scenario like 'driving to a heist' or 'a pigeon's big day out' and build the perfect soundtrack.",
          "A small, silly job that uses the bit of your brain that likes being clever.",
          "Send it to someone without explaining the title."),
]


TEXT_FIELDS = ("title", "summary", "whyItWorks", "makeItBetter")


def typeset(text: str) -> str:
    """Curly quotes, to match the UI copy."""
    text = re.sub(r"(^|[\s(])'", "\\1\u2018", text)
    return text.replace("'", "\u2019")


def main() -> None:
    wb = openpyxl.load_workbook(SRC, read_only=True)
    ws = wb["Ideas"]
    rows = list(ws.iter_rows(values_only=True))
    header = rows[0]
    out = []
    for raw in rows[1:]:
        r = dict(zip(header, raw))
        rid = r["ID"]
        a = A[rid]

        company = [COMPANY[c] for c in r["Company"].split("/")]
        for extra in a.get("c", []):
            if extra not in company:
                company.append(extra)

        actions = a.get("a") or list(dict.fromkeys(x.lower() for x in r["Action type"].split("/")))

        if "cost" in a:
            cmin, ctyp, cmax = a["cost"]
        else:
            cmin, ctyp, cmax = r["Min cost (£)"], a["tc"], r["Max cost (£)"]
        if "time" in a:
            tmin, ttyp, tmax = a["time"]
        else:
            tmin, ttyp, tmax = r["Min time (mins)"], a["tt"], r["Max time (mins)"]
        # 999 in the sheet means "ongoing"; cap it at a full day.
        tmax = min(tmax, 480)

        planning = a.get("pl") or ("booking" if r["Planning"] == "Needs booking" else "same-day")

        item = {
            "id": rid,
            "title": a.get("t", r["Idea"]),
            "summary": a.get("s", r["What it means"]),
            "category": r["Category"],
            "cost": {"min": cmin, "typical": ctyp, "max": cmax},
            "time": {"minMinutes": tmin, "typicalMinutes": ttyp, "maxMinutes": tmax},
            "energy": [ENERGY[x] for x in a["e"]],
            "company": company,
            "setting": a.get("st") or SETTING[r["Location"]],
            "environment": a.get("env") or ENVIRONMENT[r["Environment"]],
            "actions": actions,
            "feelings": a["f"],
            "planning": planning,
            "novelty": r["Familiarity"].lower(),
            "personality": a.get("p") or PERSONALITY[r["Personality"]],
            "wildcardScore": a.get("w", 20),
            "whyItWorks": a["why"],
        }
        if a.get("better"):
            item["makeItBetter"] = a["better"]
        item["source"] = (
            {"type": "reddit", "url": r["Source URL"]} if r["Origin"] == "Thread" else {"type": "original"}
        )
        assert cmin <= ctyp <= cmax, rid
        assert tmin <= ttyp <= tmax, rid
        out.append(item)

    assert len(out) == 120
    out.extend(EXTRAS)
    for item in out:
        for f in TEXT_FIELDS:
            if f in item:
                item[f] = typeset(item[f])
    OUT.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {len(out)} activities to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
