// Exercise artwork. References are either a path ("assets/exercises/x.svg")
// or "idb:<id>" for an image the user added. Resolved object URLs are cached
// so a re-render never flashes the placeholder.
import { h, slugify } from "../js/utils.js";
import { imageURL } from "../js/state.js";

const resolved = new Map();

/**
 * Artwork shipped with the app, keyed by the slug of an exercise's name.
 * Generated by tools/sync-assets.mjs from whatever is in assets/exercises,
 * so adding a picture is: name the file after the exercise, drop it in, run
 * the tool. Nothing in the workout data has to change.
 */
const bundled = new Map();

export async function loadBundledArtwork() {
  try {
    const response = await fetch("assets/exercises/manifest.json");
    if (!response.ok) return;
    const data = await response.json();
    for (const [slug, file] of Object.entries(data.images || {})) bundled.set(slug, file);
  } catch {
    // Offline before the manifest was ever cached: placeholders it is.
  }
}

/** The bundled file for an item name, or null. */
export function bundledArtwork(name) {
  return bundled.get(slugify(name)) || null;
}

/** The filename this item would need, so the editor can tell the user. */
export function expectedArtworkName(name) {
  const slug = slugify(name);
  return slug ? `${slug}.png` : null;
}

export const PLACEHOLDERS = {
  exercise: "assets/exercises/placeholder.svg",
  warmup: "assets/exercises/warmup-placeholder.svg",
  cooldown: "assets/exercises/cooldown-placeholder.svg",
  none: "assets/icons/no-image.svg",
  empty: "assets/icons/empty-state.svg",
};

/** Synchronous best guess, for building DOM without awaiting. */
export function knownURL(ref) {
  if (!ref) return null;
  if (!ref.startsWith("idb:")) return ref;
  return resolved.get(ref) || null;
}

/**
 * An <img> for an exercise or stage, in order of preference:
 *   1. the image the user attached (a blob in IndexedDB, or an explicit path)
 *   2. artwork bundled with the app whose filename matches `name`
 *   3. the placeholder
 * @param {string|null} ref
 * @param {{alt?: string, placeholder?: string, name?: string}} options
 */
export function imageEl(ref, { alt = "", placeholder = PLACEHOLDERS.exercise, name = "" } = {}) {
  const fallback = (name && bundledArtwork(name)) || placeholder;
  const img = h("img", { alt, src: knownURL(ref) || fallback, decoding: "async" });
  if (ref && ref.startsWith("idb:") && !resolved.has(ref)) {
    imageURL(ref).then((url) => {
      if (!url) return;
      resolved.set(ref, url);
      img.src = url;
    });
  }
  return img;
}

/** Drops a cached URL after the underlying image is replaced or removed. */
export function forgetImage(ref) {
  resolved.delete(ref);
}
