// Exercise artwork. References are either a path ("assets/exercises/x.svg")
// or "idb:<id>" for an image the user added. Resolved object URLs are cached
// so a re-render never flashes the placeholder.
import { h, slugify } from "../js/utils.js";
import { imageURL } from "../js/state.js";
import { header, iconButton } from "./header.js";

const resolved = new Map();

/**
 * Artwork shipped with the app, keyed by the slug of an exercise's name.
 * Generated by tools/sync-assets.mjs from whatever is in assets/exercises,
 * so adding a picture is: name the file after the exercise, drop it in, run
 * the tool. Nothing in the workout data has to change.
 */
const bundled = new Map();

export async function loadBundledArtwork() {
  try {
    const response = await fetch("assets/exercises/manifest.json");
    if (!response.ok) return;
    const data = await response.json();
    for (const [slug, file] of Object.entries(data.images || {})) bundled.set(slug, file);
  } catch {
    // Offline before the manifest was ever cached: placeholders it is.
  }
}

/** The bundled file for an item name, or null. */
export function bundledArtwork(name) {
  return bundled.get(slugify(name)) || null;
}

/** The filename this item would need, so the editor can tell the user. */
export function expectedArtworkName(name) {
  const slug = slugify(name);
  return slug ? `${slug}.png` : null;
}

export const PLACEHOLDERS = {
  exercise: "assets/exercises/placeholder.svg",
  warmup: "assets/exercises/warmup-placeholder.svg",
  cooldown: "assets/exercises/cooldown-placeholder.svg",
  none: "assets/icons/no-image.svg",
  empty: "assets/icons/empty-state.svg",
};

/** Synchronous best guess, for building DOM without awaiting. */
export function knownURL(ref) {
  if (!ref) return null;
  if (!ref.startsWith("idb:")) return ref;
  return resolved.get(ref) || null;
}

/**
 * An <img> for an exercise or stage, in order of preference:
 *   1. the image the user attached (a blob in IndexedDB, or an explicit path)
 *   2. artwork bundled with the app whose filename matches `name`
 *   3. the placeholder
 * @param {string|null} ref
 * @param {{alt?: string, placeholder?: string, name?: string}} options
 */
export function imageEl(ref, { alt = "", placeholder = PLACEHOLDERS.exercise, name = "" } = {}) {
  const fallback = (name && bundledArtwork(name)) || placeholder;
  const img = h("img", { alt, src: knownURL(ref) || fallback, decoding: "async" });
  if (ref && ref.startsWith("idb:") && !resolved.has(ref)) {
    imageURL(ref).then((url) => {
      if (!url) return;
      resolved.set(ref, url);
      img.src = url;
    });
  }
  return img;
}

/** Drops a cached URL after the underlying image is replaced or removed. */
export function forgetImage(ref) {
  resolved.delete(ref);
}

/**
 * Full-screen look at an exercise picture.
 *
 * A 16:10 diagram fitted to a portrait phone is barely bigger than the
 * thumbnail, which makes the small print on a real coaching diagram useless.
 * So the viewer has two states: fit to the screen, and fit to the height —
 * which on a phone makes the picture about three times wider than the screen,
 * readable, and pannable with an ordinary drag.
 */
export function openImageViewer({ ref, name, placeholder = PLACEHOLDERS.exercise }) {
  const img = imageEl(ref, { alt: `${name} guide image`, placeholder, name });
  const body = h("div", { class: "viewer-body" });
  let zoomed = false;

  const surface = h(
    "button",
    {
      class: "viewer-surface",
      type: "button",
      "aria-label": "Zoom in",
      onclick: () => setZoom(!zoomed),
    },
    img
  );
  body.append(surface);

  const zoomButton = iconButton("expand", "Zoom in", () => setZoom(!zoomed));
  const hint = h("p", { class: "viewer-hint", text: "Tap the picture to zoom in" });

  function setZoom(next) {
    zoomed = next;
    body.classList.toggle("is-zoomed", zoomed);
    surface.setAttribute("aria-label", zoomed ? "Fit to screen" : "Zoom in");
    zoomButton.setAttribute("aria-label", zoomed ? "Fit to screen" : "Zoom in");
    hint.textContent = zoomed ? "Drag to look around" : "Tap the picture to zoom in";
    if (zoomed) {
      // Start in the middle rather than at the left edge.
      requestAnimationFrame(() => {
        body.scrollLeft = (body.scrollWidth - body.clientWidth) / 2;
      });
    } else {
      body.scrollTo(0, 0);
    }
  }

  const viewer = h(
    "div",
    { class: "viewer", role: "dialog", "aria-modal": "true", "aria-label": `${name} image` },
    header({
      title: name,
      left: zoomButton,
      right: iconButton("close", "Close image", () => viewer.remove()),
    }),
    body,
    hint
  );
  document.getElementById("overlays").append(viewer);
  return viewer;
}
