/* Stamps departures/version.js with a release number and a fingerprint of the
 * app's own source files, and names the service worker cache after it.
 *
 * The fingerprint is a hash of what actually ships, so the string shown in the
 * app can be compared against the repository: if they differ, the browser is
 * showing an older cached copy.
 *
 *   node tools/stamp-build.js                 stamp, keeping the version
 *   node tools/stamp-build.js --version 1.3   stamp and set the version
 *   node tools/stamp-build.js --check         exit 1 if the stamp is stale
 */
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const VERSION_FILE = path.join(ROOT, 'version.js');
const SW_FILE = path.join(ROOT, 'sw.js');

// Everything the browser runs, except the two files that carry the stamp
// itself — including them would be circular.
function sourceFiles() {
  const files = ['index.html', 'style.css', 'app.js', 'boot.js', 'data.js', 'words.js',
    'manifest.webmanifest'];
  fs.readdirSync(path.join(ROOT, 'games'))
    .filter(name => name.endsWith('.js'))
    .forEach(name => files.push('games/' + name));
  return files.sort();
}

function fingerprint() {
  const hash = crypto.createHash('sha256');
  sourceFiles().forEach(file => {
    hash.update(file);
    hash.update(fs.readFileSync(path.join(ROOT, file)));
  });
  return hash.digest('hex').slice(0, 7);
}

function readCurrent() {
  if (!fs.existsSync(VERSION_FILE)) return {};
  const text = fs.readFileSync(VERSION_FILE, 'utf8');
  const field = name => {
    const match = new RegExp(name + ": '([^']*)'").exec(text);
    return match ? match[1] : '';
  };
  return {
    version: field('version'),
    released: field('released'),
    fingerprint: field('fingerprint')
  };
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

const args = process.argv.slice(2);
const versionArg = args.indexOf('--version');
const current = readCurrent();
const build = {
  version: versionArg !== -1 ? args[versionArg + 1] : (current.version || '1.0'),
  fingerprint: fingerprint()
};
// The release date only moves when the contents actually change, so re-running
// the script on a quiet day does not produce a spurious diff.
build.released = (current.fingerprint === build.fingerprint && current.version === build.version)
  ? (current.released || today())
  : today();

if (args.indexOf('--check') !== -1) {
  const stale = current.fingerprint !== build.fingerprint;
  console.log('files:       ' + build.fingerprint);
  console.log('version.js:  ' + (current.fingerprint || '(none)') + (stale ? '   STALE' : '   ok'));
  const cacheName = /var CACHE = '([^']+)'/.exec(fs.readFileSync(SW_FILE, 'utf8'));
  const expected = 'departures-' + build.version + '-' + build.fingerprint;
  const cacheOk = cacheName && cacheName[1] === expected;
  console.log('sw cache:    ' + (cacheName ? cacheName[1] : '(none)') + (cacheOk ? '   ok' : '   STALE'));
  process.exit(stale || !cacheOk ? 1 : 0);
}

fs.writeFileSync(VERSION_FILE, `/* Generated by tools/stamp-build.js — do not edit by hand.
 * fingerprint is a hash of the app's source files, so the build shown in the
 * footer can be checked against the repository.
 */
window.DeparturesBuild = {
  version: '${build.version}',
  released: '${build.released}',
  fingerprint: '${build.fingerprint}'
};
`);

// Naming the cache after the fingerprint means every content change busts the
// cache on its own — no remembering to bump a number by hand.
const sw = fs.readFileSync(SW_FILE, 'utf8');
fs.writeFileSync(SW_FILE, sw.replace(/var CACHE = '[^']*';/,
  `var CACHE = 'departures-${build.version}-${build.fingerprint}';`));

console.log('version  ' + build.version);
console.log('build    ' + build.fingerprint);
console.log('released ' + build.released);
console.log('cache    departures-' + build.version + '-' + build.fingerprint);
