/* ===========================================================================
   Dino Expedition — dinosaur dataset
   ---------------------------------------------------------------------------
   Facts are written for children aged 5–10 and kept age-appropriate.
   Where scientists are still working things out, the wording says so
   ("Scientists think…", "Evidence suggests…").

   Sources used to check these facts (all free, reputable, public):
     • Natural History Museum, London — nhm.ac.uk/discover/dino-directory
     • American Museum of Natural History — amnh.org
     • Smithsonian National Museum of Natural History — naturalhistory.si.edu
     • University of California Museum of Paleontology — ucmp.berkeley.edu
     • Encyclopaedia Britannica — britannica.com
   Dates (mya = millions of years ago) follow the geologic time scale used by
   these museums. They are rounded to keep them friendly for young readers.
   =========================================================================== */

const HABITATS = {
  woodland: { id: 'woodland', name: 'Forests & Woodlands', emoji: '🌲',
    blurb: 'Leafy trees, ferns and shady places to hide.' },
  wetland:  { id: 'wetland',  name: 'Rivers & Wetlands',   emoji: '🏞️',
    blurb: 'Muddy riverbanks, swamps and plenty of water.' },
  plains:   { id: 'plains',   name: 'Open Plains',         emoji: '🌾',
    blurb: 'Wide, flat lands with low plants to munch.' },
  coast:    { id: 'coast',    name: 'Coasts & Shallow Seas', emoji: '🌊',
    blurb: 'Sandy shores and shallow water full of fish.' },
  drylands: { id: 'drylands', name: 'Dry Sandy Lands',     emoji: '🏜️',
    blurb: 'Hot, dusty deserts and dry scrubland.' },
};

const PERIODS = {
  triassic:   { id: 'triassic',   name: 'Triassic',   range: 'about 252–201 million years ago', emoji: '🌋' },
  jurassic:   { id: 'jurassic',   name: 'Jurassic',   range: 'about 201–145 million years ago', emoji: '🌿' },
  cretaceous: { id: 'cretaceous', name: 'Cretaceous', range: 'about 145–66 million years ago',  emoji: '🌸' },
};

/* diet: 'herbivore' | 'carnivore' | 'omnivore' */

/* OPTIONAL ARTWORK (see images/SOURCES.md for the full drop-in guide)
   Every creature below is PRE-FILLED with `silhouette` and `art` blocks
   containing the target filename, written alt text, and a `find` search link
   to a properly-licensed image. They are switched OFF with `ready: false`, so
   the friendly `emoji` placeholder is shown and no image is requested yet.

   TO TURN ON A REAL PICTURE:
     1. Open the `find` link, choose a CC0 / CC-BY / public-domain image.
     2. Save it into images/silhouettes/ or images/art/ using the given `file`.
     3. Set `ready: true`.
     4. Fill in `credit`, `license` and `sourceUrl` from the image's page
        (CC0 / public-domain images need no credit, but it's kind to add one).

   `credit` + `license` then appear automatically on the in-app "Image credits"
   page. Keep `art` files small (~800px wide, under ~200 KB). */

const DINOS = [
  {
    id: 'tyrannosaurus',
    silhouette: { ready: false, file: 'tyrannosaurus.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Tyrannosaurus%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'tyrannosaurus.jpg',
      alt: 'A large Tyrannosaurus rex walking on two legs, with a big head, tiny arms and a long tail',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Tyrannosaurus%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🚌', text: 'As long as a school bus' },
    name: 'Tyrannosaurus rex',
    nick: 'T. rex',
    say: 'tie-RAN-oh-SOR-us',
    emoji: '🦖',
    period: 'cretaceous',
    when: 'about 68–66 million years ago',
    diet: 'carnivore',
    sizeWord: 'Bus-sized',
    length: 'Up to 12 metres long — about as long as a bus.',
    region: 'North America',
    habitat: ['woodland', 'wetland'],
    discovery: 'The first good skeleton was found in Montana, USA, in 1902.',
    scientistsThink: 'Scientists think T. rex had one of the strongest bites of any land animal ever. Its tiny arms are still a bit of a mystery!',
    funFact: 'Its name means "tyrant lizard king".',
    source: 'Natural History Museum, London; American Museum of Natural History',
  },
  {
    id: 'triceratops',
    silhouette: { ready: false, file: 'triceratops.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Triceratops%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'triceratops.jpg',
      alt: 'A four-legged Triceratops with three horns and a wide bony neck frill',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Triceratops%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🚗', text: 'As long as two family cars in a row' },
    name: 'Triceratops',
    say: 'try-SERRA-tops',
    emoji: '🦏',
    period: 'cretaceous',
    when: 'about 68–66 million years ago',
    diet: 'herbivore',
    sizeWord: 'Rhino-ish but bigger',
    length: 'Around 9 metres long with a huge bony frill.',
    region: 'North America',
    habitat: ['plains', 'woodland'],
    discovery: 'Named in 1889 from horns found in Colorado, USA.',
    scientistsThink: 'Scientists think the big frill and three horns may have been used to show off to other Triceratops, and perhaps to stay safe.',
    funFact: 'Its name means "three-horned face".',
    source: 'Smithsonian National Museum of Natural History; Encyclopaedia Britannica',
  },
  {
    id: 'stegosaurus',
    silhouette: { ready: false, file: 'stegosaurus.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Stegosaurus%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'stegosaurus.jpg',
      alt: 'A Stegosaurus with two rows of tall bony plates along its back and spikes on its tail',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Stegosaurus%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🚗', text: 'About as long as two family cars' },
    name: 'Stegosaurus',
    say: 'STEG-oh-SOR-us',
    emoji: '🦕',
    period: 'jurassic',
    when: 'about 155–150 million years ago',
    diet: 'herbivore',
    sizeWord: 'Bus-sized',
    length: 'Up to 9 metres long with tall plates down its back.',
    region: 'North America',
    habitat: ['plains', 'woodland'],
    discovery: 'First found in Colorado, USA, in 1877.',
    scientistsThink: 'Scientists think the back plates may have helped Stegosaurus warm up, cool down, or signal to others. The spiky tail probably kept it safe.',
    funFact: 'Its brain was only about the size of a plum!',
    source: 'University of California Museum of Paleontology; Natural History Museum, London',
  },
  {
    id: 'velociraptor',
    silhouette: { ready: false, file: 'velociraptor.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Velociraptor%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'velociraptor.jpg',
      alt: 'A small, feathered Velociraptor about the size of a turkey, running on two legs',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Velociraptor%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🐕', text: 'About the size of a pet dog' },
    name: 'Velociraptor',
    say: 'vel-OSS-i-rap-tor',
    emoji: '🦃',
    period: 'cretaceous',
    when: 'about 75–71 million years ago',
    diet: 'carnivore',
    sizeWord: 'Turkey-sized',
    length: 'Only about the size of a large turkey — much smaller than in films!',
    region: 'Mongolia, Asia',
    habitat: ['drylands'],
    discovery: 'Discovered in the Gobi Desert in 1923.',
    scientistsThink: 'Evidence suggests Velociraptor was covered in feathers. Scientists found bumps on its arm bones where feathers would have attached.',
    funFact: 'Real Velociraptor was about knee-high to an adult, not big like in the movies.',
    source: 'American Museum of Natural History; Natural History Museum, London',
  },
  {
    id: 'brachiosaurus',
    silhouette: { ready: false, file: 'brachiosaurus.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Brachiosaurus%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'brachiosaurus.jpg',
      alt: 'A huge Brachiosaurus reaching its very long neck up to the tops of tall trees',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Brachiosaurus%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🏠', text: 'Tall enough to peek over a two-storey house' },
    name: 'Brachiosaurus',
    say: 'BRACK-ee-oh-SOR-us',
    emoji: '🦕',
    period: 'jurassic',
    when: 'about 154–150 million years ago',
    diet: 'herbivore',
    sizeWord: 'Taller than a house',
    length: 'Around 18 metres long and tall enough to peek over a house.',
    region: 'North America',
    habitat: ['woodland', 'plains'],
    discovery: 'Named in 1903 from bones found in Colorado, USA.',
    scientistsThink: 'Scientists think its long neck let it reach leaves high up in tall trees, like a giant crane.',
    funFact: 'Its front legs were longer than its back legs, which is quite unusual.',
    source: 'Smithsonian National Museum of Natural History; Encyclopaedia Britannica',
  },
  {
    id: 'diplodocus',
    silhouette: { ready: false, file: 'diplodocus.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Diplodocus%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'diplodocus.jpg',
      alt: 'A very long Diplodocus with an extremely long neck and whip-like tail, on four legs',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Diplodocus%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🚌', text: 'As long as two school buses end to end' },
    name: 'Diplodocus',
    say: 'dip-LOD-oh-kus',
    emoji: '🦕',
    period: 'jurassic',
    when: 'about 154–152 million years ago',
    diet: 'herbivore',
    sizeWord: 'Very, very long',
    length: 'Around 26 metres long — one of the longest dinosaurs of all.',
    region: 'North America',
    habitat: ['plains', 'wetland'],
    discovery: 'Named in 1878 from fossils found in Wyoming, USA.',
    scientistsThink: 'Scientists think Diplodocus may have used its long, thin tail like a whip to make a loud cracking sound.',
    funFact: 'A famous Diplodocus cast nicknamed "Dippy" has toured museums around the world.',
    source: 'Natural History Museum, London; University of California Museum of Paleontology',
  },
  {
    id: 'spinosaurus',
    silhouette: { ready: false, file: 'spinosaurus.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Spinosaurus%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'spinosaurus.jpg',
      alt: 'A Spinosaurus with a tall sail on its back and a long crocodile-like snout, near water',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Spinosaurus%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🚌', text: 'Even longer than a school bus' },
    name: 'Spinosaurus',
    say: 'SPINE-oh-SOR-us',
    emoji: '🐊',
    period: 'cretaceous',
    when: 'about 99–93 million years ago',
    diet: 'carnivore',
    sizeWord: 'Longer than a T. rex',
    length: 'Around 15 metres long with a tall sail on its back.',
    region: 'North Africa',
    habitat: ['wetland', 'coast'],
    discovery: 'First described in 1915 from bones found in Egypt.',
    scientistsThink: 'Evidence suggests Spinosaurus spent a lot of time in water and ate fish. Scientists are still studying how well it could swim.',
    funFact: 'It had a long, crocodile-like snout that was great for catching fish.',
    source: 'Natural History Museum, London; National Geographic Society',
  },
  {
    id: 'ankylosaurus',
    silhouette: { ready: false, file: 'ankylosaurus.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Ankylosaurus%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'ankylosaurus.jpg',
      alt: 'A heavily armoured Ankylosaurus covered in bony plates with a club on the end of its tail',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Ankylosaurus%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🦛', text: 'About as big and heavy as a hippopotamus' },
    name: 'Ankylosaurus',
    say: 'an-KIE-loh-SOR-us',
    emoji: '🐢',
    period: 'cretaceous',
    when: 'about 68–66 million years ago',
    diet: 'herbivore',
    sizeWord: 'Tank-like',
    length: 'Around 6–8 metres long and covered in bony armour.',
    region: 'North America',
    habitat: ['woodland', 'plains'],
    discovery: 'Named in 1908 from fossils found in Montana, USA.',
    scientistsThink: 'Scientists think the heavy club on its tail could swing hard enough to defend it from big predators.',
    funFact: 'Even its eyelids had bony plates for protection!',
    source: 'American Museum of Natural History; Encyclopaedia Britannica',
  },
  {
    id: 'parasaurolophus',
    silhouette: { ready: false, file: 'parasaurolophus.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Parasaurolophus%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'parasaurolophus.jpg',
      alt: 'A Parasaurolophus with a long, curved tube-shaped crest on its head, among ferns',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Parasaurolophus%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🚗', text: 'As long as two family cars' },
    name: 'Parasaurolophus',
    say: 'pa-ra-SOR-OL-off-us',
    emoji: '🦆',
    period: 'cretaceous',
    when: 'about 76–73 million years ago',
    diet: 'herbivore',
    sizeWord: 'Bigger than a car',
    length: 'Around 10 metres long with a long, curved head crest.',
    region: 'North America',
    habitat: ['woodland', 'wetland'],
    discovery: 'Named in 1922 from a skull found in Alberta, Canada.',
    scientistsThink: 'Scientists think the hollow crest may have worked like a trumpet to make deep, honking sounds to other dinosaurs.',
    funFact: 'It had hundreds of teeth packed together for grinding tough plants.',
    source: 'University of California Museum of Paleontology; Natural History Museum, London',
  },
  {
    id: 'allosaurus',
    silhouette: { ready: false, file: 'allosaurus.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Allosaurus%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'allosaurus.jpg',
      alt: 'An Allosaurus walking on two legs, with small bumpy crests above its eyes',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Allosaurus%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🚌', text: 'Nearly as long as a small bus' },
    name: 'Allosaurus',
    say: 'AL-oh-SOR-us',
    emoji: '🦖',
    period: 'jurassic',
    when: 'about 155–145 million years ago',
    diet: 'carnivore',
    sizeWord: 'Bigger than a car',
    length: 'Around 9 metres long — a top hunter of the Jurassic.',
    region: 'North America',
    habitat: ['plains', 'woodland'],
    discovery: 'Named in 1877 from fossils found in Colorado, USA.',
    scientistsThink: 'Scientists think Allosaurus may have used its head and jaws like a hatchet to attack big plant-eaters.',
    funFact: 'It had small bumpy crests above its eyes.',
    source: 'Smithsonian National Museum of Natural History; Encyclopaedia Britannica',
  },
  {
    id: 'iguanodon',
    silhouette: { ready: false, file: 'iguanodon.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Iguanodon%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'iguanodon.jpg',
      alt: 'An Iguanodon with a spiked thumb, standing on two legs',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Iguanodon%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🚗', text: 'As long as two family cars' },
    name: 'Iguanodon',
    say: 'ig-WA-no-don',
    emoji: '🦎',
    period: 'cretaceous',
    when: 'about 125 million years ago',
    diet: 'herbivore',
    sizeWord: 'Bigger than a car',
    length: 'Around 10 metres long with a spiky thumb.',
    region: 'Europe',
    habitat: ['woodland', 'plains'],
    discovery: 'One of the very first dinosaurs ever named, back in 1825 in England.',
    scientistsThink: 'Scientists think the pointy thumb spike may have been used to defend against predators or to gather food.',
    funFact: 'It could walk on two legs or all four.',
    source: 'Natural History Museum, London; Encyclopaedia Britannica',
  },
  {
    id: 'compsognathus',
    silhouette: { ready: false, file: 'compsognathus.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Compsognathus%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'compsognathus.jpg',
      alt: 'A tiny chicken-sized Compsognathus running quickly on two slender legs',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Compsognathus%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🐔', text: 'About the size of a pet chicken' },
    name: 'Compsognathus',
    say: 'komp-SOG-na-thus',
    emoji: '🐔',
    period: 'jurassic',
    when: 'about 150 million years ago',
    diet: 'carnivore',
    sizeWord: 'Chicken-sized',
    length: 'Only about the size of a chicken or small turkey.',
    region: 'Europe',
    habitat: ['coast', 'woodland'],
    discovery: 'Found in Germany in the 1850s.',
    scientistsThink: 'Scientists think this tiny, speedy hunter chased small lizards and insects.',
    funFact: 'For a long time it was one of the smallest dinosaurs known.',
    source: 'University of California Museum of Paleontology; Natural History Museum, London',
  },
];

/* Pterosaurs are NOT dinosaurs — but kids often think they are, so we include
   one with a clear, friendly note to gently correct the common mix-up. */
const NOT_DINOS = [
  {
    id: 'pteranodon',
    silhouette: { ready: false, file: 'pteranodon.svg',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Pteranodon%20silhouette',
      credit: '', license: '', sourceUrl: '' },
    art: { ready: false, file: 'pteranodon.jpg',
      alt: 'A Pteranodon flying with wide wings, a long backward head crest and a toothless beak',
      find: 'https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Pteranodon%20restoration',
      credit: '', license: '', sourceUrl: '' },
    compare: { icon: '🧒', text: 'Wings as wide as four children lying head to toe' },
    name: 'Pteranodon',
    say: 'teh-RAN-oh-don',
    emoji: '🦅',
    period: 'cretaceous',
    when: 'about 88–80 million years ago',
    diet: 'carnivore',
    sizeWord: 'Wide wings',
    length: 'Wings stretching around 6 metres from tip to tip.',
    region: 'North America',
    habitat: ['coast'],
    notADino: true,
    discovery: 'Named in 1876 from fossils found in Kansas, USA.',
    scientistsThink: 'Pteranodon was a flying reptile called a pterosaur — NOT a dinosaur, even though it lived at the same time. Scientists think it swooped over the sea to catch fish.',
    funFact: 'It had a long crest on its head and no teeth in its beak.',
    source: 'American Museum of Natural History; Natural History Museum, London',
  },
];

const ALL_CREATURES = [...DINOS, ...NOT_DINOS];

/* A few big-picture truths we want every child to take away. */
const BIG_FACTS = [
  'Birds are living dinosaurs! The chickens and sparrows you see today are the great-great-grandchildren of dinosaurs.',
  'People and big dinosaurs never lived at the same time. The last big dinosaurs died out about 66 million years ago — long, long before the first people.',
  'We learn about dinosaurs from fossils — bones, teeth, eggs and footprints that turned to stone over millions of years.',
  'Scientists called palaeontologists are still discovering brand-new dinosaurs every year.',
];

const SOURCES = [
  { name: 'Natural History Museum, London — Dino Directory', url: 'https://www.nhm.ac.uk/discover/dino-directory.html' },
  { name: 'American Museum of Natural History', url: 'https://www.amnh.org/dinosaurs' },
  { name: 'Smithsonian National Museum of Natural History', url: 'https://naturalhistory.si.edu/' },
  { name: 'University of California Museum of Paleontology', url: 'https://ucmp.berkeley.edu/' },
  { name: 'Encyclopaedia Britannica — Dinosaurs', url: 'https://www.britannica.com/animal/dinosaur' },
];
