/* Generated by tools/stamp-build.js — do not edit by hand.
 * fingerprint is a hash of the app's source files, so the build shown in the
 * footer can be checked against the repository.
 */
window.DeparturesBuild = {
  version: '1.2',
  released: '2026-07-26',
  fingerprint: '13c4a2f'
};
