/* Bobble Squad — sound.
 *
 * Every noise in this game is generated by the Web Audio API at the moment it
 * plays. There are no audio files, which means nothing to download, nothing to
 * cache and nothing that can fail offline.
 *
 * Sound is never load-bearing: anything you can hear also has a visible
 * equivalent on screen, and the whole thing can be muted from the pause menu.
 */
(function (global) {
  'use strict';

  var ctx = null;
  var master = null;
  var enabled = true;
  var ready = false;

  function init() {
    if (ctx) return true;
    var AC = global.AudioContext || global.webkitAudioContext;
    if (!AC) return false;
    try {
      ctx = new AC();
      master = ctx.createGain();
      master.gain.value = 0.32;
      master.connect(ctx.destination);
      ready = true;
    } catch (e) {
      ctx = null;
      return false;
    }
    return true;
  }

  /* Safari will not start an audio context until a real gesture happens, so
   * every input path calls this. */
  function unlock() {
    if (!init()) return;
    if (ctx.state === 'suspended') ctx.resume();
  }

  function setEnabled(v) {
    enabled = !!v;
    if (master) master.gain.value = enabled ? 0.32 : 0;
  }

  function isEnabled() { return enabled; }

  function tone(o) {
    if (!enabled || !ready) return;
    var t0 = ctx.currentTime + (o.delay || 0);
    var osc = ctx.createOscillator();
    var g = ctx.createGain();
    osc.type = o.type || 'triangle';
    osc.frequency.setValueAtTime(o.freq, t0);
    if (o.to) osc.frequency.exponentialRampToValueAtTime(Math.max(20, o.to), t0 + o.dur);
    var vol = (o.vol === undefined ? 0.5 : o.vol);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(vol, t0 + 0.012);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + o.dur);
    osc.connect(g);
    g.connect(master);
    osc.start(t0);
    osc.stop(t0 + o.dur + 0.03);
  }

  function noise(dur, vol, freq) {
    if (!enabled || !ready) return;
    var n = Math.floor(ctx.sampleRate * dur);
    var buf = ctx.createBuffer(1, n, ctx.sampleRate);
    var d = buf.getChannelData(0);
    for (var i = 0; i < n; i++) d[i] = (Math.random() * 2 - 1) * (1 - i / n);
    var src = ctx.createBufferSource();
    src.buffer = buf;
    var f = ctx.createBiquadFilter();
    f.type = 'bandpass';
    f.frequency.value = freq || 900;
    var g = ctx.createGain();
    g.gain.value = vol === undefined ? 0.35 : vol;
    src.connect(f); f.connect(g); g.connect(master);
    src.start();
  }

  // A cheerful pentatonic scale keeps every accidental combination consonant.
  var SCALE = [523.25, 587.33, 659.25, 783.99, 880.0, 1046.5, 1174.7, 1318.5];

  var S = {
    step: function () { tone({ freq: 150 + Math.random() * 40, to: 90, dur: 0.06, vol: 0.10, type: 'sine' }); },
    jump: function () { tone({ freq: 420, to: 760, dur: 0.14, vol: 0.30, type: 'triangle' }); },
    land: function () { tone({ freq: 220, to: 120, dur: 0.10, vol: 0.22, type: 'sine' }); },
    boing: function () {
      tone({ freq: 260, to: 900, dur: 0.20, vol: 0.40, type: 'sawtooth' });
      tone({ freq: 900, to: 400, dur: 0.18, vol: 0.20, type: 'sine', delay: 0.16 });
    },
    pick: function () {
      tone({ freq: 880, dur: 0.09, vol: 0.34, type: 'square' });
      tone({ freq: 1318, dur: 0.14, vol: 0.28, type: 'square', delay: 0.08 });
    },
    badge: function () {
      [659, 880, 1046, 1318].forEach(function (f, i) {
        tone({ freq: f, dur: 0.16, vol: 0.30, type: 'triangle', delay: i * 0.075 });
      });
    },
    fanfare: function () {
      [523, 659, 783, 1046, 1318].forEach(function (f, i) {
        tone({ freq: f, dur: 0.30, vol: 0.32, type: 'triangle', delay: i * 0.11 });
      });
      noise(0.5, 0.14, 2200);
    },
    honk: function () {
      tone({ freq: 300, to: 180, dur: 0.22, vol: 0.42, type: 'sawtooth' });
      tone({ freq: 452, to: 270, dur: 0.22, vol: 0.26, type: 'square' });
    },
    moo: function () {
      tone({ freq: 190, to: 130, dur: 0.5, vol: 0.36, type: 'sawtooth' });
      tone({ freq: 96, to: 70, dur: 0.55, vol: 0.20, type: 'sine' });
    },
    bubble: function () {
      for (var i = 0; i < 5; i++) {
        tone({ freq: 380 + Math.random() * 700, to: 1400, dur: 0.10, vol: 0.14, type: 'sine', delay: i * 0.055 });
      }
    },
    note: function (i) { tone({ freq: SCALE[i % SCALE.length], dur: 0.34, vol: 0.34, type: 'triangle' }); },
    scan: function () {
      tone({ freq: 620, to: 1500, dur: 0.24, vol: 0.24, type: 'sine' });
      tone({ freq: 1500, to: 620, dur: 0.22, vol: 0.14, type: 'sine', delay: 0.2 });
    },
    ping: function (closeness) {
      tone({ freq: 700 + closeness * 900, dur: 0.07, vol: 0.22, type: 'square' });
    },
    click: function () { tone({ freq: 660, dur: 0.05, vol: 0.20, type: 'square' }); },
    place: function () { tone({ freq: 300, to: 460, dur: 0.09, vol: 0.28, type: 'square' }); },
    remove: function () { tone({ freq: 460, to: 240, dur: 0.09, vol: 0.24, type: 'square' }); },
    engine: function () { tone({ freq: 110, to: 150, dur: 0.24, vol: 0.16, type: 'sawtooth' }); },
    bonk: function () {
      tone({ freq: 150, to: 70, dur: 0.18, vol: 0.30, type: 'square' });
      noise(0.14, 0.16, 400);
    },
    door: function () { tone({ freq: 180, to: 340, dur: 0.42, vol: 0.24, type: 'sawtooth' }); },
    whoosh: function () { noise(0.4, 0.20, 700); },
    splash: function () { noise(0.35, 0.24, 1500); },
    quack: function () {
      tone({ freq: 520, to: 380, dur: 0.13, vol: 0.32, type: 'sawtooth' });
      tone({ freq: 460, to: 300, dur: 0.12, vol: 0.24, type: 'sawtooth', delay: 0.15 });
    },
    reset: function () { tone({ freq: 700, to: 400, dur: 0.3, vol: 0.24, type: 'sine' }); },
    /* People say hello; only the birds quack. The two were the same sound
     * until somebody pointed out that pressing a person did nothing. */
    hello: function () {
      tone({ freq: 620, to: 780, dur: 0.13, vol: 0.30, type: 'triangle' });
      tone({ freq: 880, dur: 0.16, vol: 0.26, type: 'triangle', delay: 0.13 });
    },
    laugh: function () {
      [720, 640, 700, 600].forEach(function (f, i) {
        tone({ freq: f, to: f * 0.85, dur: 0.09, vol: 0.24, type: 'triangle', delay: i * 0.1 });
      });
    },
    hint: function () {
      tone({ freq: 520, to: 1040, dur: 0.18, vol: 0.26, type: 'sine' });
      tone({ freq: 1040, dur: 0.22, vol: 0.20, type: 'triangle', delay: 0.16 });
    },
    map: function () { tone({ freq: 380, to: 620, dur: 0.16, vol: 0.22, type: 'triangle' }); }
  };

  global.BSAudio = {
    unlock: unlock,
    setEnabled: setEnabled,
    isEnabled: isEnabled,
    play: function (name, arg) { if (S[name]) S[name](arg); }
  };
})(window);
