/* ===========================================================================
   NostalgiAI — seed content
   ---------------------------------------------------------------------------
   The little drawings, paper games and playground crafts UK millennials made
   as kids (roughly the 1990s–early 2000s), written so a grown-up and a child
   can relearn and make them together.

   CONTENT NOTES & SAFE-BY-DESIGN CHOICES
   • Every activity here is folk culture — playground games, paper folds and
     pen-and-paper doodles passed hand to hand for generations. None are owned
     by a company, so they are safe to teach and describe.
   • We deliberately do NOT use any trademarked characters, brand logos or
     copyrighted artwork as app visuals. Where an activity has a nickname tied
     to popular culture (e.g. the "Cool S"), we describe its folklore in words
     only and draw nothing branded.
   • Difficulty is "easy" | "medium" | "tricky". Era is the decade the activity
     felt most everywhere in UK schools; most are timeless.

   SCHEMA (see one object below for the canonical shape):
     id, title, emoji, category, shortDescription,
     era, ukRelevance, usRelevance,
     materials[], difficulty, timeRequired,
     steps[], safetyNotes, nostalgiaNote, tags[], related[]
   =========================================================================== */

const CATEGORIES = [
  { id: 'doodles',    name: 'Doodles & Drawings', emoji: '✏️', blurb: 'Biro and pencil-case classics — the things that filled the margins.' },
  { id: 'paper',      name: 'Paper Folding',      emoji: '📄', blurb: 'Fold, crease and fly. No glue, no scissors, just an A4 sheet.' },
  { id: 'penpaper',   name: 'Pen & Paper Games',  emoji: '🎲', blurb: 'Two players, one page, a whole wet lunchtime gone.' },
  { id: 'playground', name: 'Playground & Notes', emoji: '🤝', blurb: 'Passed-along games and secretly folded notes.' },
  { id: 'crafts',     name: 'Crafts & Makes',     emoji: '🧶', blurb: 'Wool, thread and card — the things you took home in your bag.' },
];

const DIFFICULTY = {
  easy:   { label: 'Easy',   note: 'Great for younger children' },
  medium: { label: 'Medium', note: 'A little patience needed' },
  tricky: { label: 'Tricky', note: 'Best with a grown-up to help' },
};

const ACTIVITIES = [
  /* ───────────────────────── DOODLES ───────────────────────── */
  {
    id: 'cool-s',
    title: 'The Cool "S"',
    emoji: '🅢',
    category: 'doodles',
    shortDescription: 'The pointy interlocking "S" that appeared on every exercise book, pencil case and desk in the country.',
    era: '1990s',
    ukRelevance: 'A genuine UK playground universal — almost everyone who went to school here can draw it, yet nobody remembers being taught.',
    usRelevance: 'Just as widespread in US schools, where it picked up names like the "Stussy S" and "graffiti S".',
    materials: ['A pen or pencil', 'Any scrap of paper (or the back of your hand)'],
    difficulty: 'easy',
    timeRequired: '1 min',
    steps: [
      'Draw six short vertical lines: a top group of three lines side by side, then a small gap, then a bottom group of three lines underneath.',
      'On the top group, join the two outer lines with a pointed peak (like a little roof: ∧). On the bottom group, join the two outer lines with a pointed base (a little V).',
      'Now the clever bit: draw a diagonal line from the bottom of the top-left line down to the top of the bottom-right line.',
      'Draw a second diagonal the other way, from the bottom of the top-right line to the top of the bottom-left line, so the two diagonals cross in the middle.',
      'Tidy up the crossing lines in the centre — that X is the heart of the S. Go over your outline and rub out any guide bits you do not want.',
      'Once you can do it from memory, try it big and shade one side to make it look 3D.',
    ],
    safetyNotes: '',
    nostalgiaNote: 'No teacher ever set it, no kid invented it, and yet it spread to every classroom like a secret handshake. Drawing it is basically a millennial superpower.',
    tags: ['pen', 'no materials', '60 seconds', 'classic'],
    related: ['bubble-writing', '3d-box-letters'],
  },
  {
    id: 'bubble-writing',
    title: 'Bubble Writing',
    emoji: '🫧',
    category: 'doodles',
    shortDescription: 'Fat, rounded letters for the front of every project folder and "KEEP OUT" bedroom sign.',
    era: '1990s',
    ukRelevance: 'The default font for school project covers, birthday cards and door signs across the UK.',
    usRelevance: 'Equally common in US schools — same idea, same wobbly results.',
    materials: ['Pencil', 'Pen or felt tips for outlining', 'Paper'],
    difficulty: 'easy',
    timeRequired: '5–10 mins',
    steps: [
      'Lightly write your word in normal pencil first, leaving plenty of space between each letter.',
      'Imagine each thin pencil line has been inflated like a balloon. Draw a fat outline a centimetre or so around every stroke.',
      'Where two outlines bump into each other, just let them touch — do not cross them over.',
      'Round off every corner so nothing is sharp. Bubble letters have no straight points.',
      'Go over the outline in pen, then carefully rub out the pencil guide line inside.',
      'Colour in, add a little white "shine" spot on each letter, or draw a drop shadow to make it pop.',
    ],
    safetyNotes: '',
    nostalgiaNote: 'The true test was fitting your whole name on the front of an exercise book without the last letter getting squashed against the edge.',
    tags: ['lettering', 'art', 'project cover'],
    related: ['cool-s', '3d-box-letters'],
  },
  {
    id: '3d-box-letters',
    title: '3D Block Letters & Boxes',
    emoji: '🧊',
    category: 'doodles',
    shortDescription: 'Making letters and cubes "pop off the page" by adding depth lines — the doodle that felt like magic.',
    era: '1990s',
    ukRelevance: 'A maths-lesson margin staple, usually drawn instead of doing actual maths.',
    usRelevance: 'Universal doodle — works the same everywhere.',
    materials: ['Pencil or pen', 'Paper (squared/maths paper helps)'],
    difficulty: 'easy',
    timeRequired: '3–5 mins',
    steps: [
      'Draw a simple square or a chunky capital letter as your front face.',
      'Pick one corner direction — say, up and to the right. From every corner of your shape, draw a short line going that same way and the same length.',
      'Keep all those depth lines parallel. This is the secret: same direction, same length.',
      'Join the far ends of those depth lines to complete the back edges.',
      'Rub out (or just ignore) any lines that would be hidden behind the solid shape.',
      'Shade the side and top faces a little darker than the front to make it look properly solid.',
    ],
    safetyNotes: '',
    nostalgiaNote: 'The first time the box actually looked 3D you felt like a genuine artist. Then you drew forty more in the back of your planner.',
    tags: ['lettering', '3d', 'maths paper'],
    related: ['bubble-writing', 'cool-s'],
  },
  {
    id: 'exquisite-doodle',
    title: 'Fold-Over Monster (Exquisite Corpse)',
    emoji: '👹',
    category: 'doodles',
    shortDescription: 'Everyone draws one body part without seeing the others, then you unfold the ridiculous creature.',
    era: '1990s',
    ukRelevance: 'A rainy-lunchtime and family-car-journey favourite passed round in UK classrooms.',
    usRelevance: 'Played worldwide; the posh art-school name is "exquisite corpse".',
    materials: ['Paper', 'Pens or pencils', '2 or more players'],
    difficulty: 'easy',
    timeRequired: '5 mins',
    steps: [
      'Fold a sheet of paper into three or four sections across (like a letter), then open it flat again.',
      'The first person draws a head and neck in the top section — anything they like.',
      'They fold their bit out of sight, leaving just two tiny marks where the neck lines reach the fold, so the next person knows where to start.',
      'Pass it on. The next person draws the body and arms, hides it, and leaves marks at the next fold.',
      'Carry on for legs, then feet, until every section is filled.',
      'Unfold the whole thing and meet your gloriously mismatched monster. Give it a silly name.',
    ],
    safetyNotes: '',
    nostalgiaNote: 'Best results came from one person drawing a perfectly sensible head and the rest of the creature being utter chaos.',
    tags: ['group', 'silly', 'no skill needed'],
    related: ['consequences', 'cool-s'],
  },

  /* ───────────────────────── PAPER FOLDING ───────────────────────── */
  {
    id: 'fortune-teller',
    title: 'Paper Fortune Teller (Chatterbox)',
    emoji: '🔮',
    category: 'paper',
    shortDescription: 'The folded finger game with colours, numbers and a secret message or fortune hidden inside each flap.',
    era: '1990s',
    ukRelevance: 'Known in the UK as a "chatterbox", "fortune teller" or "salt cellar" — a true playground institution.',
    usRelevance: 'Called a "cootie catcher" or "fortune teller" in the US; same fold, same fun.',
    materials: ['One square sheet of paper', 'Pens or felt tips', '(Optional) scissors to square off A4'],
    difficulty: 'medium',
    timeRequired: '10 mins',
    steps: [
      'Start with a perfect square. If you only have A4, fold one corner over to meet the opposite edge and trim off the spare strip so you are left with a square.',
      'Fold the square corner to corner both ways to make an X crease, then open it flat.',
      'Fold all four corners into the very centre. You now have a smaller square.',
      'Turn the whole thing over and again fold all four corners into the centre. Smaller square again.',
      'Fold it in half and in half the other way to loosen the creases, then slide your thumbs and first fingers under the four square flaps on the bottom — that is the working "mouth".',
      'Open it out flat to decorate: write four colours on the outside flaps, the numbers 1–8 on the inside triangles, and lift each numbered triangle to write a fortune or dare underneath.',
      'To play: a friend picks a colour, you spell it out opening and closing the chatterbox for each letter, they pick a number, you count it out, they pick a final number — lift that flap and read their fortune.',
    ],
    safetyNotes: 'If you are squaring off A4 with scissors, younger children should ask a grown-up to do the cutting.',
    nostalgiaNote: 'Half the fun was writing the fortunes: "you will marry your crush", "you smell of cheese", and the dreaded "you have to do a dare".',
    tags: ['folding', 'finger game', 'fortunes', 'two-player'],
    related: ['paper-aeroplane', 'mash', 'water-bomb'],
  },
  {
    id: 'paper-aeroplane',
    title: 'Classic Paper Aeroplane (The Dart)',
    emoji: '✈️',
    category: 'paper',
    shortDescription: 'The simple, fast dart that everyone could fold from memory — the king of bored-lesson aircraft.',
    era: '1990s',
    ukRelevance: 'The default UK playground and classroom plane, usually launched the second the teacher turned around.',
    usRelevance: 'The same universal "dart" design known the world over.',
    materials: ['One sheet of A4 paper'],
    difficulty: 'easy',
    timeRequired: '3 mins',
    steps: [
      'Fold the sheet in half lengthways (the long way, like a hot dog) to make a centre crease, then open it back up.',
      'Fold the top two corners in so they meet neatly at that centre crease, making a pointy top.',
      'Fold those slanted edges in to the centre crease again, so the point gets long and sharp.',
      'Fold the whole plane in half along the original centre crease, so the folded flaps are on the outside.',
      'Fold each side down to make the wings: line the top edge up with the bottom edge of the body and crease firmly. Do the same on the other side.',
      'Open the wings out flat, hold underneath near the point, and throw with a smooth forward flick — not a downward chuck.',
    ],
    safetyNotes: 'Aim for open space, never at faces. The pointy nose can poke an eye.',
    nostalgiaNote: 'There was always one kid who insisted their secret fold made it go twice as far. It never did, but we always tried it.',
    tags: ['folding', 'flying', 'quick'],
    related: ['fortune-teller', 'water-bomb', 'paper-football'],
  },
  {
    id: 'water-bomb',
    title: 'Paper Water Bomb',
    emoji: '💧',
    category: 'paper',
    shortDescription: 'A folded paper cube you blow up like a balloon — fill with water for outdoor mischief, or leave empty as a dice.',
    era: '1990s',
    ukRelevance: 'A summer-holiday and last-day-of-term classic in UK gardens and playgrounds.',
    usRelevance: 'Known as a "water bomb" or "paper balloon" in the US too.',
    materials: ['One square sheet of paper', '(Optional) water and a brave volunteer'],
    difficulty: 'tricky',
    timeRequired: '10–15 mins',
    steps: [
      'Start with a square. Fold it in half both ways to make a cross crease, then turn over and fold corner to corner both ways.',
      'Push the side creases inwards so the paper collapses down into a triangle with two flaps on each side (this is the classic "waterbomb base").',
      'Take the bottom point of the top layer and fold it up to the top point. Do the same on the back. You now have a square with a loose point on each side.',
      'Fold the left and right corners of the top layer into the middle. Repeat on the back.',
      'Fold the top points down and tuck each one neatly into the little pockets you just made. Repeat on the back — this is the fiddly bit.',
      'Find the small hole at one end. Blow into it firmly and the whole thing puffs up into a cube.',
      'Carefully fill with a little water through the hole for the outdoor version — or leave it empty and use it as a soft paper dice.',
    ],
    safetyNotes: 'Water versions are an outdoor-only, mind-who-you-aim-at game. Keep it well away from anyone who would rather stay dry, and tidy up soggy paper afterwards.',
    nostalgiaNote: 'Getting all four points tucked in was a genuine rite of passage. The first successful "puff" felt like winning.',
    tags: ['folding', 'outdoor', 'summer'],
    related: ['fortune-teller', 'paper-aeroplane'],
  },
  {
    id: 'folded-note',
    title: 'The Secretly Folded Note',
    emoji: '💌',
    category: 'paper',
    shortDescription: 'Folding a passed note into a tight little parcel that tucked into itself — no envelope, teacher-proof.',
    era: '1990s',
    ukRelevance: 'The original UK classroom messaging app: written in lessons, folded under the desk, passed along the row.',
    usRelevance: 'Same secret art in US schools — endless regional folds existed.',
    materials: ['A note already written on a sheet of paper', 'A friend two desks away'],
    difficulty: 'easy',
    timeRequired: '2 mins',
    steps: [
      'Write your note, then fold the paper in half lengthways twice, so you have a long thin strip.',
      'Fold the top corner down diagonally to make a triangle, then keep flipping that triangle over and over down the strip (like folding a flag).',
      'When you reach the end you will have one square-ish triangle pack with a small flap and a little pocket left over.',
      'Tuck the leftover flap firmly into the pocket so the whole note locks shut without any tape.',
      'Write the recipient\'s initials on the front and pass it along — discreetly.',
    ],
    safetyNotes: 'Kindness rule for kids: notes are for nice messages and jokes, never for leaving anyone out or being unkind.',
    nostalgiaNote: 'The folding was half the message. A beautifully tucked note said you cared; a scrappy one said you wrote it in a hurry under the desk.',
    tags: ['folding', 'secret', 'friendship'],
    related: ['fortune-teller', 'consequences'],
  },

  /* ───────────────────────── PEN & PAPER GAMES ───────────────────────── */
  {
    id: 'mash',
    title: 'MASH — Your Future, Decided',
    emoji: '🏠',
    category: 'penpaper',
    shortDescription: 'A fortune-telling game that maps out where you\'ll live, who you\'ll marry, your job, car and number of kids.',
    era: '1990s',
    ukRelevance: 'A staple of UK exercise-book margins and sleepovers; "MASH" stands for Mansion, Apartment, Shack, House.',
    usRelevance: 'Originally an American game that crossed over and became huge in UK playgrounds too.',
    materials: ['Paper', 'A pen', 'Two players (a fortune-teller and a victim)'],
    difficulty: 'easy',
    timeRequired: '5–10 mins',
    steps: [
      'Write MASH at the top — that is your four homes: Mansion, Apartment, Shack, House.',
      'Make a few more categories with the player\'s choices: who you\'ll marry (3 names — sneak in one awful one), your job, your car, how many kids, where you\'ll live.',
      'For each category, write four options: three the player suggests and one silly or dreadful one chosen by the fortune-teller.',
      'Ask the player to say "stop" while you draw a spiral. The number of loops in the spiral is your magic number.',
      'Now count through every option in order, crossing one out each time you reach your magic number. When only one option is left in a category, circle it.',
      'Skip any crossed-out options as you keep counting round and round until every category has just one survivor.',
      'Read out their gloriously random future. Commiserations if you end up in the shack with the awful match and eleven kids.',
    ],
    safetyNotes: '',
    nostalgiaNote: 'It was never really about the future. It was about whether your best mate would put your secret crush in the good column or the shack.',
    tags: ['fortunes', 'two-player', 'classic'],
    related: ['fortune-teller', 'dots-and-boxes', 'consequences'],
  },
  {
    id: 'dots-and-boxes',
    title: 'Dots and Boxes',
    emoji: '🔲',
    category: 'penpaper',
    shortDescription: 'Join the dots one line at a time; complete a box to claim it and get another go. Most boxes wins.',
    era: '1990s',
    ukRelevance: 'The go-to two-player game for the back of an exercise book during a boring lesson.',
    usRelevance: 'Played everywhere under names like "dots and boxes" or "boxes".',
    materials: ['Squared or plain paper', 'A pen each (different colours help)', 'Two players'],
    difficulty: 'easy',
    timeRequired: '5–10 mins',
    steps: [
      'Draw a grid of dots — a 6×6 grid of dots is a good first game (bigger grids take longer).',
      'Take turns to draw a single horizontal or vertical line joining two dots that are next to each other.',
      'If your line completes the fourth side of a little box, write your initial inside it — and take another turn straight away.',
      'Keep going until every possible line is drawn and the whole grid is full of boxes.',
      'Count up the boxes with your initial. Whoever owns the most wins.',
      'Top tip for older players: try not to be the one forced to draw the third side of a box, or you hand a freebie to your opponent.',
    ],
    safetyNotes: '',
    nostalgiaNote: 'Deceptively simple, secretly tactical, and the cause of many "you went twice!" arguments.',
    tags: ['two-player', 'strategy', 'grid'],
    related: ['mash', 'consequences'],
  },
  {
    id: 'consequences',
    title: 'Consequences',
    emoji: '📝',
    category: 'penpaper',
    shortDescription: 'Each player writes one line of a story, folds it over, and passes on — read aloud, the results are absurd.',
    era: '1990s',
    ukRelevance: 'A classic UK family and classroom word game, often the wordy cousin of the fold-over monster.',
    usRelevance: 'Known and played in similar forms internationally.',
    materials: ['Paper', 'Pens', 'A few players (the more the better)'],
    difficulty: 'easy',
    timeRequired: '5 mins',
    steps: [
      'Everyone has a strip of paper. The set lines are: (1) a man\'s name, (2) "met", (3) a woman\'s or another name, (4) "at/where they met", (5) "he said", (6) "she said", (7) "and the consequence was…".',
      'Write the first line at the top, then fold the paper over to hide what you wrote and pass it to the person on your left.',
      'On the new strip in front of you, write the next line, fold it over to hide it, and pass on again.',
      'Keep going down the list of lines, folding and passing each time, until all seven lines are done.',
      'Pass one last time, unfold, and take turns reading the complete, nonsensical stories out loud.',
      'Bonus: swap the prompts for whatever your group finds funny — silly places, made-up jobs, famous names.',
    ],
    safetyNotes: '',
    nostalgiaNote: 'There is no joy quite like unfolding the paper to discover the Queen met your maths teacher behind the bike sheds.',
    tags: ['group', 'words', 'silly'],
    related: ['exquisite-doodle', 'mash', 'folded-note'],
  },
  {
    id: 'paper-football',
    title: 'Flick Paper Football',
    emoji: '🏉',
    category: 'penpaper',
    shortDescription: 'A tightly folded paper triangle flicked across a desk to score "field goals" through your opponent\'s fingers.',
    era: '1990s',
    ukRelevance: 'A reliable desk game for the end of a lesson when the work was finished (or abandoned).',
    usRelevance: 'Hugely popular in the US as "paper football" or "flick football".',
    materials: ['A strip of paper (a third of an A4 sheet, lengthways)', 'A flat desk', 'Two players'],
    difficulty: 'easy',
    timeRequired: '5–10 mins',
    steps: [
      'Take a long strip of paper and fold the bottom corner up to make a triangle, then keep flipping that triangle over and over up the strip — just like folding a flag.',
      'Tuck the last little flap into the pocket so you have a tight, solid paper triangle.',
      'To score, rest your "ball" near the edge of the desk and flick it with your finger so part of it overhangs the far edge without falling off — that\'s a touchdown.',
      'For a "field goal", your opponent makes goalposts with two thumbs up and index fingers touching. Flick the triangle so it sails through the gap.',
      'Agree your points and take turns. First to an agreed score wins.',
      'House rule: if the ball flies off the desk, the other player gets a free flick.',
    ],
    safetyNotes: 'Flick along the desk, not at people — a hard-folded triangle can sting if it hits a face.',
    nostalgiaNote: 'A perfectly folded football was prized kit. Some kids kept the same one in their pencil case for an entire term.',
    tags: ['two-player', 'desk game', 'folding'],
    related: ['paper-aeroplane', 'dots-and-boxes'],
  },

  /* ───────────────────────── CRAFTS & MAKES ───────────────────────── */
  {
    id: 'friendship-bracelet',
    title: 'Candy-Stripe Friendship Bracelet',
    emoji: '🧵',
    category: 'crafts',
    shortDescription: 'Knotted embroidery-thread bracelets in diagonal stripes — made for your best mate, swapped at break.',
    era: '1990s',
    ukRelevance: 'A summer-fete and sleepover staple; the diagonal "candy stripe" was everyone\'s first pattern.',
    usRelevance: 'Equally iconic at US summer camps, where they\'re a classic camp craft.',
    materials: ['Embroidery thread in 3–4 colours', 'Scissors', 'Tape or a safety pin to anchor it'],
    difficulty: 'medium',
    timeRequired: '30–45 mins',
    steps: [
      'Cut 3 or 4 lengths of thread, each about 70cm long. Knot them together near one end, leaving a small loop or tail.',
      'Tape the knot to a table or pin it to a cushion or your jeans so it stays put and the threads hang down in order.',
      'Spread the threads out left to right and remember their order — that order is your pattern.',
      'Take the far-left thread. Make a "4" shape over the thread next to it, pass the end through and pull up tight. Do that same knot twice on each thread, working left to right.',
      'When your starting thread reaches the far right, it has made one full diagonal stripe. Drop it and start again with the new far-left thread.',
      'Keep repeating. The stripes build up diagonally and the colours cycle round in the order you laid them out.',
      'When it is long enough to wrap your wrist, knot all the threads together, plait the loose ends, and tie it on a friend.',
    ],
    safetyNotes: 'Scissors needed — younger children should have a grown-up do the cutting and help anchor the threads.',
    nostalgiaNote: 'You did not buy a friendship bracelet, you earned one. Giving someone the one you\'d spent all weekend making was a serious statement.',
    tags: ['thread', 'knots', 'gift', 'patient'],
    related: ['french-knitting', 'pom-pom'],
  },
  {
    id: 'french-knitting',
    title: 'French Knitting (Knitting Nancy)',
    emoji: '🧶',
    category: 'crafts',
    shortDescription: 'Looping wool around pins on a cotton reel to "knit" a long woollen tube or "snake".',
    era: '1990s',
    ukRelevance: 'A classic UK craft, often made on a wooden cotton reel with four panel pins hammered in the top.',
    usRelevance: 'Known in the US as "spool knitting" — same idea, sometimes a shop-bought knitting spool.',
    materials: ['A French-knitting "dolly" (or a cotton reel with 4 small nails/pins in the top)', 'A ball of wool', 'A blunt darning needle or matchstick to lift loops'],
    difficulty: 'medium',
    timeRequired: '20+ mins (grows over days)',
    steps: [
      'Push the loose end of the wool down through the hole in the middle of the reel, leaving a tail hanging out the bottom.',
      'Loop the wool once around each of the four pins, going round in the same direction. You now have a loop on each pin.',
      'Lay the wool around the outside of the next pin, above its loop.',
      'Use the needle or matchstick to lift the bottom loop up and over the top strand and off the pin — leaving the new strand as the loop. Move to the next pin and repeat.',
      'Keep going round and round, lifting the old loop over the new strand each time. Gently pull the tail hanging out the bottom now and then.',
      'A woollen tube slowly appears out of the bottom of the reel. Keep knitting until it is as long as you like.',
      'To finish, cut the wool, thread the end through the four loops, lift them off the pins and pull tight.',
    ],
    safetyNotes: 'Homemade reels have small nails or pins — a grown-up should make the dolly and supervise the needle.',
    nostalgiaNote: 'Hours of looping produced a woolly snake that absolutely nobody knew what to do with — and that was completely fine.',
    tags: ['wool', 'slow craft', 'repetitive'],
    related: ['friendship-bracelet', 'pom-pom'],
  },
  {
    id: 'pom-pom',
    title: 'Cardboard-Ring Pom-Poms',
    emoji: '🟡',
    category: 'crafts',
    shortDescription: 'Winding wool around two cardboard rings to make a fluffy pom-pom for hats, bags and keyrings.',
    era: '1990s',
    ukRelevance: 'A rainy-day and craft-lesson staple, made with two rings cut from a cereal box.',
    usRelevance: 'A universal wool craft made the same way the world over.',
    materials: ['Cardboard (a cereal box is perfect)', 'A ball of wool', 'Scissors', 'Something round to draw two circles'],
    difficulty: 'medium',
    timeRequired: '20–30 mins',
    steps: [
      'Draw two matching circles on the cardboard (about the size of a drinks coaster), each with a smaller circle in the middle, and cut them out so you have two cardboard rings (doughnut shapes).',
      'Hold the two rings together. Wind wool round and round through the middle hole and over the outside, all the way around, until the centre hole is almost full.',
      'When the hole is packed tight, push the points of your scissors between the two cardboard rings at the outside edge and snip all the wool around the rim.',
      'Ease the two rings slightly apart and tie a separate length of wool tightly around the middle, between the cards, in a firm double knot.',
      'Slide the cardboard rings off (or tear them away) and fluff up the ball.',
      'Trim any straggly bits with scissors to make it nice and round. Leave the tying-wool long if you want to attach it to a hat or bag.',
    ],
    safetyNotes: 'Lots of cutting and snipping — younger children should have a grown-up do the scissor work.',
    nostalgiaNote: 'Everyone made one. Almost nobody made a perfectly round one. The wonky ones were loved just as much.',
    tags: ['wool', 'cardboard', 'recycling'],
    related: ['french-knitting', 'friendship-bracelet'],
  },
];

/* Expose for app.js (no modules / build step). */
window.NOSTALGIAI = { CATEGORIES, DIFFICULTY, ACTIVITIES };
